In [2]:
from q42.scripts import converter
import importlib 
importlib.reload(converter)
converter.Main.split_csv_all(source_dir=f'~/.qlib/binance_data/source/1min', target_dir=f'testdata/source/1440d')

processing RUNEUSDT.csv (1/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=741168),m=Int64Index([12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=741168),path=testdata/source/1440d/0000/RUNEUSDT.csv
sub_df(0)=
                       open    high     low   close      volume    symbol
date
2020-09-04 07:12:00  0.7473  0.9512  0.6487  0.8284  12836673.0  RUNEUSDT
2020-09-04 07:13:00  0.7064  0.9512  0.6487  0.8326  12705483.0  RUNEUSDT
2020-09-04 07:14:00  0.7070  0.9512  0.6487  0.8292  12670846.0  RUNEUSDT
2020-09-04 07:15:00  0.7014  0.9512  0.6487  0.8296  12625452.0  RUNEUSDT
2020-09-04 07:16:00  0.7005  0.9512  0.6487  0.8320  12601629.0  RUNEUSDT
...                     ...     ...     ...     ...         ...       ...
2022-01-31 23:55:00  4.1220     NaN     NaN     NaN         NaN  RUNEUSDT
2022-01-31 23:56:00  4.1230     NaN     NaN     NaN         NaN  RUNEUSDT
2022-01-31 23:57:00  4.1270     NaN     NaN     NaN         NaN  RUNEUSDT
2022-01-31 23:58:00  4.1260     NaN     NaN     NaN         NaN  RUNEUSDT
2022-01-31 23:59:00  4.1220     NaN     NaN     NaN         NaN  RUNEUSDT

[741168 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume    symbol
0   2020-09-05  0.8113  0.8548  0.5520  0.6389   8341556.0  RUNEUSDT
1   2020-09-06  0.6389  0.8058  0.6151  0.7792   5396643.0  RUNEUSDT
2   2020-09-07  0.7775  0.8045  0.6236  0.7220   5245473.0  RUNEUSDT
3   2020-09-08  0.7217  0.7625  0.6493  0.6961   4530651.0  RUNEUSDT
4   2020-09-09  0.6951  0.7668  0.6537  0.7290   4578630.0  RUNEUSDT
..         ...     ...     ...     ...     ...         ...       ...
509 2022-01-27  4.0750  4.1270  3.7850  3.9860  14229641.0  RUNEUSDT
510 2022-01-28  3.9860  4.1220  3.8120  4.0310  11924773.0  RUNEUSDT
511 2022-01-29  4.0310  4.3300  4.0160  4.2320   9567575.0  RUNEUSDT
512 2022-01-30  4.2320  4.2730  3.9300  4.0100   8492197.0  RUNEUSDT
513 2022-01-31  4.0100  4.1420  3.8060  4.1210  10994693.0  RUNEUSDT

[514 rows x 7 columns]
processing ALPHAUSDT.csv (2/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=625980),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=625980),path=testdata/source/1440d/0000/ALPHAUSDT.csv
sub_df(0)=
                        open     high      low    close      volume     symbol
date
2020-11-23 07:00:00  0.20001  0.24636  0.17799  0.23303  66199951.0  ALPHAUSDT
2020-11-23 07:01:00  0.21943  0.24636  0.17799  0.23207  65826211.0  ALPHAUSDT
2020-11-23 07:02:00  0.21760  0.24636  0.17799  0.23270  65599077.0  ALPHAUSDT
2020-11-23 07:03:00  0.21579  0.24636  0.17799  0.23319  65199081.0  ALPHAUSDT
2020-11-23 07:04:00  0.21498  0.24636  0.17799  0.23223  65128261.0  ALPHAUSDT
...                      ...      ...      ...      ...         ...        ...
2022-01-31 23:55:00  0.38300      NaN      NaN      NaN         NaN  ALPHAUSDT
2022-01-31 23:56:00  0.38360      NaN      NaN      NaN         NaN  ALPHAUSDT
2022-01-31 23:57:00  0.38360      NaN      NaN      NaN         NaN  ALPHAUSDT
2022-01-31 23:58:00  0.38350      NaN      NaN      NaN         NaN  ALPHAUSDT
2022-01-31 23:59:00  0.38310      NaN      NaN      NaN         NaN  ALPHAUSDT

[625980 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close       volume     symbol
0   2020-11-24  0.19257  0.28800  0.18312  0.26739  101162652.0  ALPHAUSDT
1   2020-11-25  0.26793  0.28200  0.22262  0.24533   46153790.0  ALPHAUSDT
2   2020-11-26  0.24450  0.24863  0.17860  0.21294   64950755.0  ALPHAUSDT
3   2020-11-27  0.21327  0.24564  0.20640  0.21975   35853989.0  ALPHAUSDT
4   2020-11-28  0.21975  0.23758  0.19461  0.22440   37567148.0  ALPHAUSDT
..         ...      ...      ...      ...      ...          ...        ...
429 2022-01-27  0.39060  0.39670  0.35570  0.37120  127066417.0  ALPHAUSDT
430 2022-01-28  0.37110  0.37990  0.35750  0.37700   69601523.0  ALPHAUSDT
431 2022-01-29  0.37700  0.39560  0.37420  0.39080   54657557.0  ALPHAUSDT
432 2022-01-30  0.39070  0.39990  0.37250  0.37650   49688702.0  ALPHAUSDT
433 2022-01-31  0.37640  0.38490  0.35730  0.38280   63382542.0  ALPHAUSDT

[434 rows x 7 columns]
processing NKNUSDT.csv (3/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=428700),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=428700),path=testdata/source/1440d/0000/NKNUSDT.csv
sub_df(0)=
                        open   high      low    close       volume   symbol
date
2021-04-09 07:00:00  1.18000  1.484  1.06982  1.16535  218769586.0  NKNUSDT
2021-04-09 07:01:00  1.12600  1.484  1.06982  1.16850  218819128.0  NKNUSDT
2021-04-09 07:02:00  1.09200  1.484  1.06982  1.17500  218755179.0  NKNUSDT
2021-04-09 07:03:00  1.10792  1.484  1.06982  1.18056  218683979.0  NKNUSDT
2021-04-09 07:04:00  1.10397  1.484  1.06982  1.17630  218681390.0  NKNUSDT
...                      ...    ...      ...      ...          ...      ...
2022-01-31 23:55:00  0.22126    NaN      NaN      NaN          NaN  NKNUSDT
2022-01-31 23:56:00  0.22103    NaN      NaN      NaN          NaN  NKNUSDT
2022-01-31 23:57:00  0.22088    NaN      NaN      NaN          NaN  NKNUSDT
2022-01-31 23:58:00  0.22068    NaN      NaN      NaN          NaN  NKNUSDT
2022-01-31 23:59:00  0.22052    NaN      NaN      NaN          NaN  NKNUSDT

[428700 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close       volume   symbol
0   2021-04-10  1.29483  1.32848  0.98336  1.02558  143947257.0  NKNUSDT
1   2021-04-11  1.02558  1.06434  0.92240  0.95244   94044054.0  NKNUSDT
2   2021-04-12  0.95413  0.98000  0.85000  0.87208   90756168.0  NKNUSDT
3   2021-04-13  0.87244  0.93664  0.82200  0.85092   62032500.0  NKNUSDT
4   2021-04-14  0.85296  0.85811  0.73000  0.78793  106313829.0  NKNUSDT
..         ...      ...      ...      ...      ...          ...      ...
292 2022-01-27  0.20098  0.20721  0.18719  0.19496   92285595.0  NKNUSDT
293 2022-01-28  0.19493  0.20313  0.18800  0.20288   63118607.0  NKNUSDT
294 2022-01-29  0.20292  0.21300  0.20192  0.21172   48610605.0  NKNUSDT
295 2022-01-30  0.21181  0.21933  0.20080  0.21381   78732240.0  NKNUSDT
296 2022-01-31  0.21383  0.22553  0.19604  0.22073  300087043.0  NKNUSDT

[297 rows x 7 columns]
processing BLZUSDT.csv (4/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=722458),m=Int64Index([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=722458),path=testdata/source/1440d/0000/BLZUSDT.csv
sub_df(0)=
                        open   high      low    close     volume   symbol
date
2020-09-17 07:02:00  0.11770  0.124  0.11347  0.11954  9797045.0  BLZUSDT
2020-09-17 07:03:00  0.11712  0.124  0.11347  0.11987  9745267.0  BLZUSDT
2020-09-17 07:04:00  0.11575  0.124  0.11347  0.11986  9591035.0  BLZUSDT
2020-09-17 07:05:00  0.11571  0.124  0.11347  0.11986  9561327.0  BLZUSDT
2020-09-17 07:06:00  0.11664  0.124  0.11347  0.12011  9555145.0  BLZUSDT
...                      ...    ...      ...      ...        ...      ...
2022-01-31 23:55:00  0.13077    NaN      NaN      NaN        NaN  BLZUSDT
2022-01-31 23:56:00  0.13072    NaN      NaN      NaN        NaN  BLZUSDT
2022-01-31 23:57:00  0.13072    NaN      NaN      NaN        NaN  BLZUSDT
2022-01-31 23:58:00  0.13065    NaN      NaN      NaN        NaN  BLZUSDT
2022-01-31 23:59:00  0.13051    NaN      NaN      NaN        NaN  BLZUSDT

[722458 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close       volume   symbol
0   2020-09-18  0.11980  0.12400  0.11425  0.11870    9095068.0  BLZUSDT
1   2020-09-19  0.11870  0.11991  0.11027  0.11647    7174037.0  BLZUSDT
2   2020-09-20  0.11649  0.11896  0.10000  0.10457   13428398.0  BLZUSDT
3   2020-09-21  0.10457  0.10575  0.08149  0.08451   18323372.0  BLZUSDT
4   2020-09-22  0.08450  0.08957  0.08216  0.08726    9282156.0  BLZUSDT
..         ...      ...      ...      ...      ...          ...      ...
496 2022-01-27  0.12207  0.12560  0.11562  0.11965  118297037.0  BLZUSDT
497 2022-01-28  0.11967  0.12815  0.11749  0.12772  114205184.0  BLZUSDT
498 2022-01-29  0.12772  0.13313  0.12687  0.13055  103967850.0  BLZUSDT
499 2022-01-30  0.13048  0.13440  0.12541  0.12736  100949381.0  BLZUSDT
500 2022-01-31  0.12734  0.13095  0.12100  0.13036  108989845.0  BLZUSDT

[501 rows x 7 columns]
processing BNBBUSD.csv (5/145)

h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=270510),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=270510),path=testdata/source/1440d/0000/BNBBUSD.csv
sub_df(0)=
                       open    high     low   close    volume   symbol
date
2021-07-28 03:30:00  312.45  327.82  303.32  310.09  15150.56  BNBBUSD
2021-07-28 03:31:00  312.60  327.82  303.32  310.20  15148.98  BNBBUSD
2021-07-28 03:32:00  314.44  327.82  303.32  310.17  15137.98  BNBBUSD
2021-07-28 03:33:00  314.44  327.82  303.32  309.84  15157.84  BNBBUSD
2021-07-28 03:34:00  314.04  327.82  303.32  309.83  15148.42  BNBBUSD
...                     ...     ...     ...     ...       ...      ...
2022-01-31 23:55:00  376.21     NaN     NaN     NaN       NaN  BNBBUSD
2022-01-31 23:56:00  375.40     NaN     NaN     NaN       NaN  BNBBUSD
2022-01-31 23:57:00  375.52     NaN     NaN     NaN       NaN  BNBBUSD
2022-01-31 23:58:00  375.02     NaN     NaN     NaN       NaN  BNBBUSD
2022-01-31 23:59:00  374.65     NaN     NaN     NaN       NaN  BNBBUSD

[270510 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close     volume   symbol
0   2021-07-29  313.48  320.38  308.11  316.80   14687.66  BNBBUSD
1   2021-07-30  316.83  325.56  306.01  322.32   22630.50  BNBBUSD
2   2021-07-31  322.50  338.46  317.50  332.08   22847.02  BNBBUSD
3   2021-08-01  332.08  347.93  328.60  332.60   31533.99  BNBBUSD
4   2021-08-02  332.52  338.11  326.40  330.60   32558.34  BNBBUSD
..         ...     ...     ...     ...     ...        ...      ...
182 2022-01-27  374.91  392.93  358.67  389.44  286416.96  BNBBUSD
183 2022-01-28  389.34  395.71  375.49  385.95  209443.13  BNBBUSD
184 2022-01-29  385.91  397.24  380.51  389.04  128886.02  BNBBUSD
185 2022-01-30  389.09  389.37  372.18  377.03  133487.75  BNBBUSD
186 2022-01-31  377.00  385.14  365.02  374.56  145556.12  BNBBUSD

[187 rows x 7 columns]
processing RLCUSDT.csv (6/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=791580),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=791580),path=testdata/source/1440d/0000/RLCUSDT.csv
sub_df(0)=
                       open    high     low   close      volume   symbol
date
2020-07-31 07:00:00  1.1255  1.2599  1.1255  1.1859  13687772.1  RLCUSDT
2020-07-31 07:01:00  1.1550  1.2599  1.1343  1.1871  13696587.4  RLCUSDT
2020-07-31 07:02:00  1.1750  1.2599  1.1343  1.1880  13692257.0  RLCUSDT
2020-07-31 07:03:00  1.1816  1.2599  1.1343  1.1883  13697269.8  RLCUSDT
2020-07-31 07:04:00  1.1623  1.2599  1.1500  1.1907  13693246.3  RLCUSDT
...                     ...     ...     ...     ...         ...      ...
2022-01-31 23:55:00  1.9501     NaN     NaN     NaN         NaN  RLCUSDT
2022-01-31 23:56:00  1.9516     NaN     NaN     NaN         NaN  RLCUSDT
2022-01-31 23:57:00  1.9533     NaN     NaN     NaN         NaN  RLCUSDT
2022-01-31 23:58:00  1.9508     NaN     NaN     NaN         NaN  RLCUSDT
2022-01-31 23:59:00  1.9502     NaN     NaN     NaN         NaN  RLCUSDT

[791580 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume   symbol
0   2020-08-01  1.1808  1.2387  1.1242  1.1437  12050419.9  RLCUSDT
1   2020-08-02  1.1432  1.1633  0.9000  1.0882  14280854.1  RLCUSDT
2   2020-08-03  1.0882  1.1290  1.0510  1.0715   9708546.4  RLCUSDT
3   2020-08-04  1.0709  1.2387  1.0679  1.2137  14329527.5  RLCUSDT
4   2020-08-05  1.2157  1.2678  1.1480  1.1727   9448169.7  RLCUSDT
..         ...     ...     ...     ...     ...         ...      ...
544 2022-01-27  1.7353  1.8700  1.6335  1.7674  19837937.7  RLCUSDT
545 2022-01-28  1.7675  1.8426  1.7244  1.8226  12391617.7  RLCUSDT
546 2022-01-29  1.8225  1.9392  1.8159  1.9152   8271940.3  RLCUSDT
547 2022-01-30  1.9158  1.9562  1.8463  1.9041   7725108.9  RLCUSDT
548 2022-01-31  1.9040  1.9983  1.7820  1.9483   9569423.6  RLCUSDT

[549 rows x 7 columns]
processing NEARUSDT.csv (7/145)
h=Int64Index([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=682080),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=682080),path=testdata/source/1440d/0000/NEARUSDT.csv
sub_df(0)=
                        open    high     low   close      volume    symbol
date
2020-10-15 08:00:00   1.0625  1.2231  0.9274  0.9359  24604254.0  NEARUSDT
2020-10-15 08:01:00   1.1286  1.2231  0.9274  0.9347  24622959.0  NEARUSDT
2020-10-15 08:02:00   1.1330  1.2231  0.9274  0.9351  24627557.0  NEARUSDT
2020-10-15 08:03:00   1.1322  1.2231  0.9274  0.9335  24642477.0  NEARUSDT
2020-10-15 08:04:00   1.1360  1.2231  0.9274  0.9341  24628426.0  NEARUSDT
...                      ...     ...     ...     ...         ...       ...
2022-01-31 23:55:00  11.0840     NaN     NaN     NaN         NaN  NEARUSDT
2022-01-31 23:56:00  11.0940     NaN     NaN     NaN         NaN  NEARUSDT
2022-01-31 23:57:00  11.1070     NaN     NaN     NaN         NaN  NEARUSDT
2022-01-31 23:58:00  11.1230     NaN     NaN     NaN         NaN  NEARUSDT
2022-01-31 23:59:00  11.1340     NaN     NaN     NaN         NaN  NEARUSDT

[682080 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close      volume    symbol
0   2020-10-16   1.1210   1.1585   0.8112   0.8156  30730886.0  NEARUSDT
1   2020-10-17   0.8175   0.8660   0.7195   0.8079  31125587.0  NEARUSDT
2   2020-10-18   0.8079   0.8740   0.7988   0.8702  14539580.0  NEARUSDT
3   2020-10-19   0.8702   0.8718   0.7704   0.8014  13018718.0  NEARUSDT
4   2020-10-20   0.8013   0.8114   0.6695   0.6769  14388068.0  NEARUSDT
..         ...      ...      ...      ...      ...         ...       ...
468 2022-01-27  11.2710  11.7470   9.9320  10.5240  65432273.0  NEARUSDT
469 2022-01-28  10.5240  10.8830  10.0520  10.7630  48205152.0  NEARUSDT
470 2022-01-29  10.7630  11.3600  10.6400  11.0400  33887761.0  NEARUSDT
471 2022-01-30  11.0390  11.1540  10.2510  10.3450  26895199.0  NEARUSDT
472 2022-01-31  10.3470  11.3950  10.0140  11.1120  37235842.0  NEARUSDT

[473 rows x 7 columns]
processing DENTUSDT.csv (8/145)
h=Int64Index([ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=451919),m=Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=451919),path=testdata/source/1440d/0000/DENTUSDT.csv
sub_df(0)=
                         open   high       low     close        volume  \
date
2021-03-24 04:01:00  0.012000  0.012  0.008392  0.009907  1.122355e+10
2021-03-24 04:02:00  0.011003  0.012  0.009012  0.009904  1.121526e+10
2021-03-24 04:03:00  0.011063  0.012  0.009012  0.009889  1.121313e+10
2021-03-24 04:04:00  0.011097  0.012  0.009012  0.009776  1.121372e+10
2021-03-24 04:05:00  0.011090  0.012  0.009012  0.009751  1.121628e+10
...                       ...    ...       ...       ...           ...
2022-01-31 23:55:00  0.002623    NaN       NaN       NaN           NaN
2022-01-31 23:56:00  0.002623    NaN       NaN       NaN           NaN
2022-01-31 23:57:00  0.002628    NaN       NaN       NaN           NaN
2022-01-31 23:58:00  0.002627    NaN       NaN       NaN           NaN
2022-01-31 23:59:00  0.002626    NaN       NaN       NaN           NaN

                       symbol
date
2021-03-24 04:01:00  DENTUSDT
2021-03-24 04:02:00  DENTUSDT
2021-03-24 04:03:00  DENTUSDT
2021-03-24 04:04:00  DENTUSDT
2021-03-24 04:05:00  DENTUSDT
...                       ...
2022-01-31 23:55:00  DENTUSDT
2022-01-31 23:56:00  DENTUSDT
2022-01-31 23:57:00  DENTUSDT
2022-01-31 23:58:00  DENTUSDT
2022-01-31 23:59:00  DENTUSDT

[451919 rows x 6 columns]
sub_df(1)=
          date      open      high       low     close        volume    symbol
0   2021-03-25  0.009520  0.011398  0.009381  0.009788  9.877483e+09  DENTUSDT
1   2021-03-26  0.009791  0.011550  0.009759  0.010579  6.948709e+09  DENTUSDT
2   2021-03-27  0.010567  0.011349  0.010150  0.010276  4.575916e+09  DENTUSDT
3   2021-03-28  0.010279  0.011293  0.009655  0.010103  6.248929e+09  DENTUSDT
4   2021-03-29  0.010103  0.012650  0.010068  0.011946  1.044781e+10  DENTUSDT
..         ...       ...       ...       ...       ...           ...       ...
308 2022-01-27  0.002530  0.002561  0.002357  0.002448  1.642547e+10  DENTUSDT
309 2022-01-28  0.002448  0.002562  0.002417  0.002534  1.368670e+10  DENTUSDT
310 2022-01-29  0.002534  0.002640  0.002529  0.002599  1.294398e+10  DENTUSDT
311 2022-01-30  0.002600  0.002640  0.002465  0.002510  1.126689e+10  DENTUSDT
312 2022-01-31  0.002509  0.002635  0.002382  0.002621  1.314312e+10  DENTUSDT

[313 rows x 7 columns]
processing SUSHIUSDT.csv (9/145)

h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=741180),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=741180),path=testdata/source/1440d/0000/SUSHIUSDT.csv
sub_df(0)=
                       open    high     low   close     volume     symbol
date
2020-09-04 07:00:00  4.6000  5.7615  4.1713  4.4330  9705849.0  SUSHIUSDT
2020-09-04 07:01:00  4.7321  5.7615  4.1713  4.4202  9693266.0  SUSHIUSDT
2020-09-04 07:02:00  4.7610  5.7615  4.1713  4.4127  9685357.0  SUSHIUSDT
2020-09-04 07:03:00  4.7829  5.7615  4.1713  4.4075  9672252.0  SUSHIUSDT
2020-09-04 07:04:00  4.7679  5.7615  4.1713  4.3955  9670094.0  SUSHIUSDT
...                     ...     ...     ...     ...        ...        ...
2022-01-31 23:55:00  4.2290     NaN     NaN     NaN        NaN  SUSHIUSDT
2022-01-31 23:56:00  4.2310     NaN     NaN     NaN        NaN  SUSHIUSDT
2022-01-31 23:57:00  4.2360     NaN     NaN     NaN        NaN  SUSHIUSDT
2022-01-31 23:58:00  4.2320     NaN     NaN     NaN        NaN  SUSHIUSDT
2022-01-31 23:59:00  4.2300     NaN     NaN     NaN        NaN  SUSHIUSDT

[741180 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close       volume     symbol
0   2020-09-05  4.5440  5.0686  1.1250  1.8868  112724401.0  SUSHIUSDT
1   2020-09-06  1.8868  3.5349  1.0204  3.1756  195214186.0  SUSHIUSDT
2   2020-09-07  3.1761  3.3940  2.0902  2.8544  116607401.0  SUSHIUSDT
3   2020-09-08  2.8547  2.9815  2.2743  2.3762   63146418.0  SUSHIUSDT
4   2020-09-09  2.3777  3.1920  2.1447  2.8782   84303606.0  SUSHIUSDT
..         ...     ...     ...     ...     ...          ...        ...
509 2022-01-27  4.2610  4.2870  3.8500  4.0490   47419009.0  SUSHIUSDT
510 2022-01-28  4.0480  4.2120  3.9260  4.1580   39367394.0  SUSHIUSDT
511 2022-01-29  4.1590  4.3190  4.1030  4.1870   31410525.0  SUSHIUSDT
512 2022-01-30  4.1870  4.3580  3.9970  4.0830   27983965.0  SUSHIUSDT
513 2022-01-31  4.0830  4.3080  3.8650  4.2220   39207042.0  SUSHIUSDT

[514 rows x 7 columns]
processing AAVEUSDT.csv (10/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=680700),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=680700),path=testdata/source/1440d/0000/AAVEUSDT.csv
sub_df(0)=
                        open    high    low   close    volume    symbol
date
2020-10-16 07:00:00   44.550  45.040  37.51  40.175  399422.6  AAVEUSDT
2020-10-16 07:01:00   40.755  43.324  38.46  40.181  398746.3  AAVEUSDT
2020-10-16 07:02:00   41.169  43.324  38.46  40.183  398783.0  AAVEUSDT
2020-10-16 07:03:00   41.057  43.324  38.46  40.150  398541.7  AAVEUSDT
2020-10-16 07:04:00   40.616  43.324  38.46  40.171  398300.1  AAVEUSDT
...                      ...     ...    ...     ...       ...       ...
2022-01-31 23:55:00  157.420     NaN    NaN     NaN       NaN  AAVEUSDT
2022-01-31 23:56:00  157.490     NaN    NaN     NaN       NaN  AAVEUSDT
2022-01-31 23:57:00  157.640     NaN    NaN     NaN       NaN  AAVEUSDT
2022-01-31 23:58:00  157.620     NaN    NaN     NaN       NaN  AAVEUSDT
2022-01-31 23:59:00  157.680     NaN    NaN     NaN       NaN  AAVEUSDT

[680700 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close    volume    symbol
0   2020-10-17   39.415   43.329   38.460   41.393  385497.7  AAVEUSDT
1   2020-10-18   41.379   41.400   39.455   40.795  370900.1  AAVEUSDT
2   2020-10-19   40.746   41.009   35.828   36.075  398700.9  AAVEUSDT
3   2020-10-20   36.083   36.474   31.889   32.135  640193.9  AAVEUSDT
4   2020-10-21   32.095   37.099   31.716   35.107  542288.7  AAVEUSDT
..         ...      ...      ...      ...      ...       ...       ...
467 2022-01-27  146.410  151.400  137.350  144.400  707635.5  AAVEUSDT
468 2022-01-28  144.390  150.660  139.200  148.860  653875.0  AAVEUSDT
469 2022-01-29  148.830  156.940  147.620  153.840  428415.9  AAVEUSDT
470 2022-01-30  153.900  155.450  145.740  148.760  360726.6  AAVEUSDT
471 2022-01-31  148.730  158.590  141.500  157.490  525705.0  AAVEUSDT

[472 rows x 7 columns]
processing LRCUSDT.csv (11/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=676375),m=Int64Index([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=676375),path=testdata/source/1440d/0000/LRCUSDT.csv
sub_df(0)=
                        open     high      low    close      volume   symbol
date
2020-10-19 07:05:00  0.15500  0.18237  0.15355  0.16869  31609181.0  LRCUSDT
2020-10-19 07:06:00  0.17544  0.18237  0.16080  0.16862  31606172.0  LRCUSDT
2020-10-19 07:07:00  0.17439  0.18237  0.16080  0.16866  31549941.0  LRCUSDT
2020-10-19 07:08:00  0.17365  0.18237  0.16080  0.16864  31421404.0  LRCUSDT
2020-10-19 07:09:00  0.17300  0.18237  0.16080  0.16852  31371890.0  LRCUSDT
...                      ...      ...      ...      ...         ...      ...
2022-01-31 23:55:00  0.99780      NaN      NaN      NaN         NaN  LRCUSDT
2022-01-31 23:56:00  0.99920      NaN      NaN      NaN         NaN  LRCUSDT
2022-01-31 23:57:00  0.99950      NaN      NaN      NaN         NaN  LRCUSDT
2022-01-31 23:58:00  0.99980      NaN      NaN      NaN         NaN  LRCUSDT
2022-01-31 23:59:00  0.99900      NaN      NaN      NaN         NaN  LRCUSDT

[676375 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close       volume   symbol
0   2020-10-20  0.17099  0.17580  0.15503  0.15685   12875504.0  LRCUSDT
1   2020-10-21  0.15694  0.17366  0.15646  0.16449    9683800.0  LRCUSDT
2   2020-10-22  0.16461  0.17379  0.16461  0.16926    4506621.0  LRCUSDT
3   2020-10-23  0.16909  0.17104  0.16135  0.16531    3567075.0  LRCUSDT
4   2020-10-24  0.16510  0.16732  0.16288  0.16609    2904167.0  LRCUSDT
..         ...      ...      ...      ...      ...          ...      ...
464 2022-01-27  1.07630  1.12750  0.92340  0.96120  423437015.0  LRCUSDT
465 2022-01-28  0.96120  1.00900  0.91070  0.98730  244758213.0  LRCUSDT
466 2022-01-29  0.98730  1.01520  0.95480  0.97310  141449048.0  LRCUSDT
467 2022-01-30  0.97320  1.05930  0.95180  1.00120  200563482.0  LRCUSDT
468 2022-01-31  1.00120  1.04030  0.92200  0.99760  174860514.0  LRCUSDT

[469 rows x 7 columns]
processing DOTUSDT.csv (12/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=759900),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=759900),path=testdata/source/1440d/0000/DOTUSDT.csv
sub_df(0)=
                       open   high    low  close      volume   symbol
date
2020-08-22 07:00:00   2.920  5.100  2.920  4.155  41314663.2  DOTUSDT
2020-08-22 07:01:00   3.083  4.563  2.990  4.155  41316792.4  DOTUSDT
2020-08-22 07:02:00   3.039  4.563  3.004  4.159  41316757.5  DOTUSDT
2020-08-22 07:03:00   3.011  4.563  3.004  4.147  41318310.1  DOTUSDT
2020-08-22 07:04:00   3.027  4.563  3.004  4.150  41319544.5  DOTUSDT
...                     ...    ...    ...    ...         ...      ...
2022-01-31 23:55:00  19.403    NaN    NaN    NaN         NaN  DOTUSDT
2022-01-31 23:56:00  19.412    NaN    NaN    NaN         NaN  DOTUSDT
2022-01-31 23:57:00  19.417    NaN    NaN    NaN         NaN  DOTUSDT
2022-01-31 23:58:00  19.406    NaN    NaN    NaN         NaN  DOTUSDT
2022-01-31 23:59:00  19.392    NaN    NaN    NaN         NaN  DOTUSDT

[759900 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close        volume   symbol
0   2020-08-23   4.482   4.500   3.706   3.993  2.302180e+07  DOTUSDT
1   2020-08-24   3.993   4.810   3.755   4.594  2.713179e+07  DOTUSDT
2   2020-08-25   4.585   5.776   4.492   5.560  5.437966e+07  DOTUSDT
3   2020-08-26   5.560   6.598   5.102   6.092  5.103190e+07  DOTUSDT
4   2020-08-27   6.092   6.828   5.230   5.668  7.522419e+07  DOTUSDT
..         ...     ...     ...     ...     ...           ...      ...
522 2022-01-27  18.059  18.469  17.120  18.091  2.698449e+07  DOTUSDT
523 2022-01-28  18.090  18.481  17.333  18.318  2.126494e+07  DOTUSDT
524 2022-01-29  18.317  19.044  18.061  18.724  1.428052e+07  DOTUSDT
525 2022-01-30  18.724  18.985  17.777  18.118  1.609781e+07  DOTUSDT
526 2022-01-31  18.118  19.600  17.109  19.368  2.460851e+07  DOTUSDT

[527 rows x 7 columns]
processing ATAUSDT.csv (13/145)

h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=221550),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=221550),path=testdata/source/1440d/0000/ATAUSDT.csv
sub_df(0)=
                       open    high   low   close      volume   symbol
date
2021-08-31 03:30:00  1.5405  1.6809  1.32  1.4026  34080214.0  ATAUSDT
2021-08-31 03:31:00  1.6047  1.6809  1.32  1.3944  33609561.0  ATAUSDT
2021-08-31 03:32:00  1.5801  1.6809  1.32  1.3939  33255250.0  ATAUSDT
2021-08-31 03:33:00  1.5929  1.6809  1.32  1.3872  33088831.0  ATAUSDT
2021-08-31 03:34:00  1.6085  1.6809  1.32  1.3929  32821778.0  ATAUSDT
...                     ...     ...   ...     ...         ...      ...
2022-01-31 23:55:00  0.3986     NaN   NaN     NaN         NaN  ATAUSDT
2022-01-31 23:56:00  0.3986     NaN   NaN     NaN         NaN  ATAUSDT
2022-01-31 23:57:00  0.3987     NaN   NaN     NaN         NaN  ATAUSDT
2022-01-31 23:58:00  0.3988     NaN   NaN     NaN         NaN  ATAUSDT
2022-01-31 23:59:00  0.3985     NaN   NaN     NaN         NaN  ATAUSDT

[221550 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close       volume   symbol
0   2021-09-01  1.3814  1.4693  1.3200  1.4104   31221780.0  ATAUSDT
1   2021-09-02  1.4105  1.4667  1.3307  1.3540   29085535.0  ATAUSDT
2   2021-09-03  1.3546  1.4034  1.2810  1.3202   27379608.0  ATAUSDT
3   2021-09-04  1.3203  1.6068  1.2928  1.3896  104555378.0  ATAUSDT
4   2021-09-05  1.3896  1.4500  1.3540  1.4124   56577711.0  ATAUSDT
..         ...     ...     ...     ...     ...          ...      ...
148 2022-01-27  0.3794  0.3943  0.3620  0.3808   24999902.0  ATAUSDT
149 2022-01-28  0.3808  0.4007  0.3758  0.3976   26315363.0  ATAUSDT
150 2022-01-29  0.3977  0.4141  0.3961  0.4117   18951157.0  ATAUSDT
151 2022-01-30  0.4118  0.4198  0.3913  0.4010   22166298.0  ATAUSDT
152 2022-01-31  0.4010  0.4027  0.3751  0.3980   20878124.0  ATAUSDT

[153 rows x 7 columns]
processing DOGEUSDT.csv (14/145)
h=Int64Index([ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=821700),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=821700),path=testdata/source/1440d/0000/DOGEUSDT.csv
sub_df(0)=
                         open      high      low     close        volume  \
date
2020-07-10 09:00:00  0.003989  0.003989  0.00334  0.003703  9.816604e+09
2020-07-10 09:01:00  0.003818  0.003977  0.00338  0.003708  9.804917e+09
2020-07-10 09:02:00  0.003834  0.003977  0.00338  0.003707  9.781848e+09
2020-07-10 09:03:00  0.003835  0.003977  0.00338  0.003706  9.763342e+09
2020-07-10 09:04:00  0.003796  0.003977  0.00338  0.003693  9.730706e+09
...                       ...       ...      ...       ...           ...
2022-01-31 23:55:00  0.141590       NaN      NaN       NaN           NaN
2022-01-31 23:56:00  0.141700       NaN      NaN       NaN           NaN
2022-01-31 23:57:00  0.141680       NaN      NaN       NaN           NaN
2022-01-31 23:58:00  0.141630       NaN      NaN       NaN           NaN
2022-01-31 23:59:00  0.141610       NaN      NaN       NaN           NaN

                       symbol
date
2020-07-10 09:00:00  DOGEUSDT
2020-07-10 09:01:00  DOGEUSDT
2020-07-10 09:02:00  DOGEUSDT
2020-07-10 09:03:00  DOGEUSDT
2020-07-10 09:04:00  DOGEUSDT
...                       ...
2022-01-31 23:55:00  DOGEUSDT
2022-01-31 23:56:00  DOGEUSDT
2022-01-31 23:57:00  DOGEUSDT
2022-01-31 23:58:00  DOGEUSDT
2022-01-31 23:59:00  DOGEUSDT

[821700 rows x 6 columns]
sub_df(1)=
          date      open      high       low     close        volume    symbol
0   2020-07-11  0.003535  0.003960  0.003411  0.003812  6.154155e+09  DOGEUSDT
1   2020-07-12  0.003810  0.003861  0.003573  0.003648  2.832683e+09  DOGEUSDT
2   2020-07-13  0.003647  0.003660  0.002942  0.003159  7.754496e+09  DOGEUSDT
3   2020-07-14  0.003159  0.003401  0.003014  0.003293  4.978543e+09  DOGEUSDT
4   2020-07-15  0.003293  0.003293  0.003046  0.003088  3.104188e+09  DOGEUSDT
..         ...       ...       ...       ...       ...           ...       ...
565 2022-01-27  0.143100  0.145930  0.136060  0.141410  2.528360e+09  DOGEUSDT
566 2022-01-28  0.141410  0.142610  0.137700  0.141350  2.070623e+09  DOGEUSDT
567 2022-01-29  0.141350  0.144160  0.140020  0.142890  1.561642e+09  DOGEUSDT
568 2022-01-30  0.142880  0.143660  0.137910  0.139040  1.578072e+09  DOGEUSDT
569 2022-01-31  0.139040  0.142460  0.136170  0.141480  1.855544e+09  DOGEUSDT

[570 rows x 7 columns]
processing ROSEUSDT.csv (15/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=45870),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=45870),path=testdata/source/1440d/0000/ROSEUSDT.csv
sub_df(0)=
                        open     high   low    close       volume    symbol
date
2021-12-31 03:30:00  0.41367  0.44813  0.39  0.43231  151850281.0  ROSEUSDT
2021-12-31 03:31:00  0.41050  0.44813  0.39  0.43332  151831001.0  ROSEUSDT
2021-12-31 03:32:00  0.41152  0.44813  0.39  0.43333  151622568.0  ROSEUSDT
2021-12-31 03:33:00  0.41145  0.44813  0.39  0.43337  151566790.0  ROSEUSDT
2021-12-31 03:34:00  0.41275  0.44813  0.39  0.43362  151511102.0  ROSEUSDT
...                      ...      ...   ...      ...          ...       ...
2022-01-31 23:55:00  0.32272      NaN   NaN      NaN          NaN  ROSEUSDT
2022-01-31 23:56:00  0.32274      NaN   NaN      NaN          NaN  ROSEUSDT
2022-01-31 23:57:00  0.32270      NaN   NaN      NaN          NaN  ROSEUSDT
2022-01-31 23:58:00  0.32240      NaN   NaN      NaN          NaN  ROSEUSDT
2022-01-31 23:59:00  0.32227      NaN   NaN      NaN          NaN  ROSEUSDT

[45870 rows x 6 columns]
sub_df(1)=
         date     open     high      low    close        volume    symbol
0  2022-01-01  0.42764  0.45490  0.42452  0.44578  2.404786e+08  ROSEUSDT
1  2022-01-02  0.44578  0.44747  0.40586  0.41585  1.672625e+08  ROSEUSDT
2  2022-01-03  0.41576  0.44009  0.39000  0.42633  2.112156e+08  ROSEUSDT
3  2022-01-04  0.42633  0.44800  0.40012  0.40239  1.450696e+08  ROSEUSDT
4  2022-01-05  0.40254  0.42576  0.33998  0.38361  2.017373e+08  ROSEUSDT
5  2022-01-06  0.38375  0.40750  0.35487  0.39763  2.347793e+08  ROSEUSDT
6  2022-01-07  0.39723  0.40000  0.35072  0.35737  1.795611e+08  ROSEUSDT
7  2022-01-08  0.35737  0.38660  0.33149  0.34268  2.460554e+08  ROSEUSDT
8  2022-01-09  0.34283  0.34879  0.31768  0.33852  2.558892e+08  ROSEUSDT
9  2022-01-10  0.33835  0.36785  0.30303  0.36072  4.887283e+08  ROSEUSDT
10 2022-01-11  0.36072  0.44800  0.36072  0.44667  1.413373e+09  ROSEUSDT
11 2022-01-12  0.44665  0.53800  0.44134  0.51929  1.790544e+09  ROSEUSDT
12 2022-01-13  0.51926  0.53880  0.47406  0.49381  8.666909e+08  ROSEUSDT
13 2022-01-14  0.49381  0.57960  0.47500  0.56556  1.011393e+09  ROSEUSDT
14 2022-01-15  0.56535  0.59443  0.54899  0.56460  8.789192e+08  ROSEUSDT
15 2022-01-16  0.56452  0.56622  0.51650  0.52309  5.557917e+08  ROSEUSDT
16 2022-01-17  0.52309  0.54800  0.48451  0.49725  7.653350e+08  ROSEUSDT
17 2022-01-18  0.49725  0.53388  0.45804  0.48233  6.741932e+08  ROSEUSDT
18 2022-01-19  0.48230  0.51385  0.45269  0.45355  6.077418e+08  ROSEUSDT
19 2022-01-20  0.45364  0.48341  0.40977  0.42044  7.104963e+08  ROSEUSDT
20 2022-01-21  0.42039  0.43408  0.35231  0.36740  8.168041e+08  ROSEUSDT
21 2022-01-22  0.36712  0.38675  0.27915  0.30700  9.929762e+08  ROSEUSDT
22 2022-01-23  0.30712  0.36962  0.30450  0.35109  7.623593e+08  ROSEUSDT
23 2022-01-24  0.35107  0.35138  0.28761  0.32640  8.803393e+08  ROSEUSDT
24 2022-01-25  0.32615  0.33800  0.29676  0.31759  6.155500e+08  ROSEUSDT
25 2022-01-26  0.31730  0.36442  0.30230  0.31377  7.319295e+08  ROSEUSDT
26 2022-01-27  0.31365  0.32699  0.29405  0.31130  4.184738e+08  ROSEUSDT
27 2022-01-28  0.31129  0.31546  0.28920  0.31032  4.573880e+08  ROSEUSDT
28 2022-01-29  0.31044  0.34323  0.30740  0.32539  4.799077e+08  ROSEUSDT
29 2022-01-30  0.32539  0.33207  0.30754  0.31371  2.507668e+08  ROSEUSDT
30 2022-01-31  0.31379  0.32718  0.29715  0.32249  3.070265e+08  ROSEUSDT
processing FTTBUSD.csv (16/145)

h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=210029),m=Int64Index([31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=210029),path=testdata/source/1440d/0000/FTTBUSD.csv
sub_df(0)=
                       open    high     low   close    volume   symbol
date
2021-09-08 03:31:00  66.664  80.318  61.783  78.380  705641.8  FTTBUSD
2021-09-08 03:32:00  66.454  80.318  61.783  78.417  706033.9  FTTBUSD
2021-09-08 03:33:00  67.243  80.318  61.783  78.644  706129.2  FTTBUSD
2021-09-08 03:34:00  67.554  80.318  61.783  78.694  706007.8  FTTBUSD
2021-09-08 03:35:00  68.866  80.318  61.783  78.702  705542.7  FTTBUSD
...                     ...     ...     ...     ...       ...      ...
2022-01-31 23:55:00  43.621     NaN     NaN     NaN       NaN  FTTBUSD
2022-01-31 23:56:00  43.619     NaN     NaN     NaN       NaN  FTTBUSD
2022-01-31 23:57:00  43.641     NaN     NaN     NaN       NaN  FTTBUSD
2022-01-31 23:58:00  43.614     NaN     NaN     NaN       NaN  FTTBUSD
2022-01-31 23:59:00  43.623     NaN     NaN     NaN       NaN  FTTBUSD

[210029 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close     volume   symbol
0   2021-09-09  76.400  85.516  72.000  79.553  1733601.4  FTTBUSD
1   2021-09-10  79.560  83.980  69.853  72.942  1698365.4  FTTBUSD
2   2021-09-11  72.864  77.273  71.847  72.613   858093.8  FTTBUSD
3   2021-09-12  72.636  78.212  70.903  73.641   751872.4  FTTBUSD
4   2021-09-13  73.625  74.288  64.530  68.431   850766.6  FTTBUSD
..         ...     ...     ...     ...     ...        ...      ...
140 2022-01-27  36.458  39.916  35.070  38.296  1033230.3  FTTBUSD
141 2022-01-28  38.270  40.219  37.589  40.001   763758.6  FTTBUSD
142 2022-01-29  39.996  41.943  39.870  41.707   433407.6  FTTBUSD
143 2022-01-30  41.712  41.895  40.193  41.060   401365.0  FTTBUSD
144 2022-01-31  41.049  44.151  39.510  43.575  1142864.6  FTTBUSD

[145 rows x 7 columns]
processing ENJUSDT.csv (17/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=705180),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=705180),path=testdata/source/1440d/0000/ENJUSDT.csv
sub_df(0)=
                        open     high      low    close      volume   symbol
date
2020-09-29 07:00:00  0.18970  0.18970  0.15045  0.15895  40986286.0  ENJUSDT
2020-09-29 07:01:00  0.17401  0.18291  0.15045  0.15876  40972109.0  ENJUSDT
2020-09-29 07:02:00  0.17416  0.18291  0.15045  0.15912  40967095.0  ENJUSDT
2020-09-29 07:03:00  0.17596  0.18291  0.15045  0.15908  40921990.0  ENJUSDT
2020-09-29 07:04:00  0.17526  0.18291  0.15045  0.15800  40753523.0  ENJUSDT
...                      ...      ...      ...      ...         ...      ...
2022-01-31 23:55:00  1.87920      NaN      NaN      NaN         NaN  ENJUSDT
2022-01-31 23:56:00  1.88440      NaN      NaN      NaN         NaN  ENJUSDT
2022-01-31 23:57:00  1.88470      NaN      NaN      NaN         NaN  ENJUSDT
2022-01-31 23:58:00  1.88520      NaN      NaN      NaN         NaN  ENJUSDT
2022-01-31 23:59:00  1.88230      NaN      NaN      NaN         NaN  ENJUSDT

[705180 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close      volume   symbol
0   2020-09-30  0.16049  0.16468  0.15390  0.16094  15999488.0  ENJUSDT
1   2020-10-01  0.16094  0.16610  0.14961  0.15411  11751573.0  ENJUSDT
2   2020-10-02  0.15382  0.15474  0.14266  0.15016   8566272.0  ENJUSDT
3   2020-10-03  0.15041  0.15412  0.14823  0.14979   3373453.0  ENJUSDT
4   2020-10-04  0.14980  0.15465  0.14591  0.15204   6028972.0  ENJUSDT
..         ...      ...      ...      ...      ...         ...      ...
484 2022-01-27  1.55160  1.65140  1.45310  1.57760  73663140.0  ENJUSDT
485 2022-01-28  1.57710  1.68440  1.55950  1.63630  67200724.0  ENJUSDT
486 2022-01-29  1.63630  1.75970  1.62770  1.75830  47846441.0  ENJUSDT
487 2022-01-30  1.75820  1.87670  1.72930  1.78200  78858010.0  ENJUSDT
488 2022-01-31  1.78220  1.91520  1.67890  1.88210  80694670.0  ENJUSDT

[489 rows x 7 columns]
processing FILUSDT.csv (18/145)
h=Int64Index([ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=680760),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=680760),path=testdata/source/1440d/0000/FILUSDT.csv
sub_df(0)=
                       open    high   low   close      volume   symbol
date
2020-10-16 06:00:00  60.455  60.462  24.5  30.978  12204065.6  FILUSDT
2020-10-16 06:01:00  58.356  59.367  24.5  30.955  12187297.5  FILUSDT
2020-10-16 06:02:00  56.700  59.367  24.5  30.822  12178794.6  FILUSDT
2020-10-16 06:03:00  56.850  59.367  24.5  30.666  12173483.8  FILUSDT
2020-10-16 06:04:00  57.695  59.367  24.5  30.578  12167769.5  FILUSDT
...                     ...     ...   ...     ...         ...      ...
2022-01-31 23:55:00  21.262     NaN   NaN     NaN         NaN  FILUSDT
2022-01-31 23:56:00  21.277     NaN   NaN     NaN         NaN  FILUSDT
2022-01-31 23:57:00  21.320     NaN   NaN     NaN         NaN  FILUSDT
2022-01-31 23:58:00  21.298     NaN   NaN     NaN         NaN  FILUSDT
2022-01-31 23:59:00  21.274     NaN   NaN     NaN         NaN  FILUSDT

[680760 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume   symbol
0   2020-10-17  30.205  37.500  28.100  34.700   6897928.6  FILUSDT
1   2020-10-18  34.620  35.590  30.711  31.570   3993747.3  FILUSDT
2   2020-10-19  31.527  31.850  26.660  30.080   7205885.4  FILUSDT
3   2020-10-20  30.025  30.500  27.834  29.800   3611696.2  FILUSDT
4   2020-10-21  29.816  31.517  26.400  26.400   3981233.7  FILUSDT
..         ...     ...     ...     ...     ...         ...      ...
467 2022-01-27  19.260  19.970  18.050  19.177  10794346.3  FILUSDT
468 2022-01-28  19.183  19.867  18.471  19.601   6957159.4  FILUSDT
469 2022-01-29  19.602  20.778  19.349  20.265   6988648.6  FILUSDT
470 2022-01-30  20.263  20.877  19.446  19.799   5134287.5  FILUSDT
471 2022-01-31  19.795  21.563  18.920  21.279   7648594.9  FILUSDT

[472 rows x 7 columns]
processing BALUSDT.csv (19/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=745499),m=Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=745499),path=testdata/source/1440d/0000/BALUSDT.csv
sub_df(0)=
                       open    high     low   close    volume   symbol
date
2020-09-01 07:01:00  35.000  39.153  30.724  35.039  662888.3  BALUSDT
2020-09-01 07:02:00  34.450  39.153  30.724  35.215  663276.9  BALUSDT
2020-09-01 07:03:00  37.521  39.153  30.724  35.236  661241.4  BALUSDT
2020-09-01 07:04:00  37.599  38.530  30.724  35.383  656789.1  BALUSDT
2020-09-01 07:05:00  37.385  38.530  30.724  35.472  655778.9  BALUSDT
...                     ...     ...     ...     ...       ...      ...
2022-01-31 23:55:00  12.177     NaN     NaN     NaN       NaN  BALUSDT
2022-01-31 23:56:00  12.177     NaN     NaN     NaN       NaN  BALUSDT
2022-01-31 23:57:00  12.186     NaN     NaN     NaN       NaN  BALUSDT
2022-01-31 23:58:00  12.181     NaN     NaN     NaN       NaN  BALUSDT
2022-01-31 23:59:00  12.177     NaN     NaN     NaN       NaN  BALUSDT

[745499 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close     volume   symbol
0   2020-09-02  34.677  36.419  28.345  32.081   619768.2  BALUSDT
1   2020-09-03  32.070  32.781  20.554  22.477   560301.2  BALUSDT
2   2020-09-04  22.419  23.502  20.337  22.093   478893.0  BALUSDT
3   2020-09-05  22.047  23.107  16.557  18.381   534261.5  BALUSDT
4   2020-09-06  18.376  21.542  17.101  21.263   280775.0  BALUSDT
..         ...     ...     ...     ...     ...        ...      ...
512 2022-01-27  11.681  12.216  11.053  11.459  1058657.5  BALUSDT
513 2022-01-28  11.467  11.920  11.307  11.863   884996.5  BALUSDT
514 2022-01-29  11.858  12.661  11.822  12.450   713047.3  BALUSDT
515 2022-01-30  12.456  12.539  11.861  12.099   653581.5  BALUSDT
516 2022-01-31  12.097  12.264  11.479  12.154   907207.7  BALUSDT

[517 rows x 7 columns]
processing SOLBUSD.csv (20/145)

h=Int64Index([ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=217199),m=Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=217199),path=testdata/source/1440d/0000/SOLBUSD.csv
sub_df(0)=
                        open     high      low    close    volume   symbol
date
2021-09-03 04:01:00  133.432  150.958  133.165  148.804  433195.0  SOLBUSD
2021-09-03 04:02:00  133.432  150.958  133.165  149.462  433753.0  SOLBUSD
2021-09-03 04:03:00  133.177  150.958  133.165  149.354  436421.0  SOLBUSD
2021-09-03 04:04:00  133.352  150.958  133.165  149.236  436485.0  SOLBUSD
2021-09-03 04:05:00  133.331  150.958  133.165  149.258  436852.0  SOLBUSD
...                      ...      ...      ...      ...       ...      ...
2022-01-31 23:55:00   99.660      NaN      NaN      NaN       NaN  SOLBUSD
2022-01-31 23:56:00   99.650      NaN      NaN      NaN       NaN  SOLBUSD
2022-01-31 23:57:00   99.740      NaN      NaN      NaN       NaN  SOLBUSD
2022-01-31 23:58:00   99.810      NaN      NaN      NaN       NaN  SOLBUSD
2022-01-31 23:59:00   99.740      NaN      NaN      NaN       NaN  SOLBUSD

[217199 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close     volume   symbol
0   2021-09-04  146.473  150.958  136.099  139.254   426067.0  SOLBUSD
1   2021-09-05  139.359  145.333  135.070  142.253   409574.0  SOLBUSD
2   2021-09-06  142.237  166.201  137.141  164.389   856808.0  SOLBUSD
3   2021-09-07  164.370  195.500  132.550  173.635  3130718.0  SOLBUSD
4   2021-09-08  173.664  198.435  146.859  190.999  1704401.0  SOLBUSD
..         ...      ...      ...      ...      ...        ...      ...
145 2022-01-27   92.100   94.600   85.520   89.440  1649230.0  SOLBUSD
146 2022-01-28   89.480   93.490   87.050   91.270  1333213.0  SOLBUSD
147 2022-01-29   91.270   98.930   90.440   96.130   869042.0  SOLBUSD
148 2022-01-30   96.140   97.540   91.360   93.230   604168.0  SOLBUSD
149 2022-01-31   93.210  101.340   89.210   99.470  1050187.0  SOLBUSD

[150 rows x 7 columns]
processing PEOPLEUSDT.csv (21/145)
h=Int64Index([ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=55920),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=55920),path=testdata/source/1440d/0000/PEOPLEUSDT.csv
sub_df(0)=
                        open     high     low    close       volume  \
date
2021-12-24 04:00:00  0.17220  0.17768  0.1502  0.15264  485454308.0
2021-12-24 04:01:00  0.17410  0.17768  0.1502  0.15254  485392870.0
2021-12-24 04:02:00  0.17513  0.17768  0.1502  0.15228  486987268.0
2021-12-24 04:03:00  0.17665  0.17667  0.1502  0.15254  486798510.0
2021-12-24 04:04:00  0.17532  0.17541  0.1502  0.15272  486736914.0
...                      ...      ...     ...      ...          ...
2022-01-31 23:55:00  0.09721      NaN     NaN      NaN          NaN
2022-01-31 23:56:00  0.09728      NaN     NaN      NaN          NaN
2022-01-31 23:57:00  0.09733      NaN     NaN      NaN          NaN
2022-01-31 23:58:00  0.09720      NaN     NaN      NaN          NaN
2022-01-31 23:59:00  0.09710      NaN     NaN      NaN          NaN

                         symbol
date
2021-12-24 04:00:00  PEOPLEUSDT
2021-12-24 04:01:00  PEOPLEUSDT
2021-12-24 04:02:00  PEOPLEUSDT
2021-12-24 04:03:00  PEOPLEUSDT
2021-12-24 04:04:00  PEOPLEUSDT
...                         ...
2022-01-31 23:55:00  PEOPLEUSDT
2022-01-31 23:56:00  PEOPLEUSDT
2022-01-31 23:57:00  PEOPLEUSDT
2022-01-31 23:58:00  PEOPLEUSDT
2022-01-31 23:59:00  PEOPLEUSDT

[55920 rows x 6 columns]
sub_df(1)=
         date     open     high      low    close        volume      symbol
0  2021-12-25  0.15777  0.16324  0.14052  0.14668  6.579767e+08  PEOPLEUSDT
1  2021-12-26  0.14658  0.15474  0.14115  0.14839  4.207439e+08  PEOPLEUSDT
2  2021-12-27  0.14839  0.15734  0.14515  0.14816  5.684757e+08  PEOPLEUSDT
3  2021-12-28  0.14816  0.14816  0.12000  0.12526  9.829892e+08  PEOPLEUSDT
4  2021-12-29  0.12534  0.13247  0.11200  0.11350  7.029299e+08  PEOPLEUSDT
5  2021-12-30  0.11350  0.13390  0.10443  0.12444  1.240496e+09  PEOPLEUSDT
6  2021-12-31  0.12444  0.13434  0.11188  0.11779  1.100923e+09  PEOPLEUSDT
7  2022-01-01  0.11779  0.12620  0.11779  0.12495  4.675554e+08  PEOPLEUSDT
8  2022-01-02  0.12496  0.12556  0.11613  0.12081  3.662350e+08  PEOPLEUSDT
9  2022-01-03  0.12075  0.14051  0.11841  0.12359  1.620466e+09  PEOPLEUSDT
10 2022-01-04  0.12357  0.12677  0.11700  0.11922  5.924705e+08  PEOPLEUSDT
11 2022-01-05  0.11920  0.12200  0.08962  0.10148  1.091638e+09  PEOPLEUSDT
12 2022-01-06  0.10139  0.10726  0.09199  0.10189  1.627966e+09  PEOPLEUSDT
13 2022-01-07  0.10189  0.11150  0.09050  0.10042  2.011296e+09  PEOPLEUSDT
14 2022-01-08  0.10044  0.10500  0.08962  0.09451  1.171681e+09  PEOPLEUSDT
15 2022-01-09  0.09451  0.09912  0.08541  0.08982  1.252350e+09  PEOPLEUSDT
16 2022-01-10  0.08983  0.09163  0.07300  0.07703  2.768480e+09  PEOPLEUSDT
17 2022-01-11  0.07709  0.08065  0.07129  0.07706  2.024491e+09  PEOPLEUSDT
18 2022-01-12  0.07705  0.08721  0.07678  0.08199  1.704953e+09  PEOPLEUSDT
19 2022-01-13  0.08196  0.08800  0.07730  0.07931  1.808297e+09  PEOPLEUSDT
20 2022-01-14  0.07930  0.08106  0.07240  0.07897  1.624262e+09  PEOPLEUSDT
21 2022-01-15  0.07896  0.07975  0.07508  0.07556  9.695189e+08  PEOPLEUSDT
22 2022-01-16  0.07557  0.08375  0.07320  0.08000  2.350322e+09  PEOPLEUSDT
23 2022-01-17  0.08000  0.08068  0.06455  0.06759  2.280976e+09  PEOPLEUSDT
24 2022-01-18  0.06758  0.06860  0.06058  0.06308  2.545945e+09  PEOPLEUSDT
25 2022-01-19  0.06306  0.06549  0.05650  0.05746  2.683442e+09  PEOPLEUSDT
26 2022-01-20  0.05746  0.06384  0.05187  0.05284  3.227395e+09  PEOPLEUSDT
27 2022-01-21  0.05283  0.05465  0.03844  0.04162  5.052304e+09  PEOPLEUSDT
28 2022-01-22  0.04161  0.04374  0.03216  0.03762  6.680323e+09  PEOPLEUSDT
29 2022-01-23  0.03763  0.04190  0.03394  0.03744  4.219921e+09  PEOPLEUSDT
30 2022-01-24  0.03743  0.03955  0.03050  0.03751  6.371920e+09  PEOPLEUSDT
31 2022-01-25  0.03751  0.04155  0.03652  0.04006  4.204973e+09  PEOPLEUSDT
32 2022-01-26  0.04004  0.04852  0.03822  0.04379  5.655670e+09  PEOPLEUSDT
33 2022-01-27  0.04381  0.05500  0.04150  0.05421  9.492850e+09  PEOPLEUSDT
34 2022-01-28  0.05422  0.05724  0.04968  0.05672  6.331687e+09  PEOPLEUSDT
35 2022-01-29  0.05673  0.09584  0.05443  0.09080  1.660884e+10  PEOPLEUSDT
36 2022-01-30  0.09081  0.09764  0.07419  0.07728  1.945612e+10  PEOPLEUSDT
37 2022-01-31  0.07727  0.10099  0.06976  0.09737  1.576144e+10  PEOPLEUSDT
processing TRBUSDT.csv (22/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=742619),m=Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=742619),path=testdata/source/1440d/0000/TRBUSDT.csv
sub_df(0)=
                       open    high     low   close    volume   symbol
date
2020-09-03 07:01:00  57.510  62.287  39.525  43.201  466104.0  TRBUSDT
2020-09-03 07:02:00  57.000  62.287  39.525  43.206  466221.0  TRBUSDT
2020-09-03 07:03:00  56.741  62.287  39.525  43.166  465691.8  TRBUSDT
2020-09-03 07:04:00  58.300  62.287  39.525  43.045  464690.5  TRBUSDT
2020-09-03 07:05:00  58.739  62.287  39.525  43.009  463263.5  TRBUSDT
...                     ...     ...     ...     ...       ...      ...
2022-01-31 23:55:00  20.500     NaN     NaN     NaN       NaN  TRBUSDT
2022-01-31 23:56:00  20.490     NaN     NaN     NaN       NaN  TRBUSDT
2022-01-31 23:57:00  20.510     NaN     NaN     NaN       NaN  TRBUSDT
2022-01-31 23:58:00  20.530     NaN     NaN     NaN       NaN  TRBUSDT
2022-01-31 23:59:00  20.520     NaN     NaN     NaN       NaN  TRBUSDT

[742619 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close    volume   symbol
0   2020-09-04  43.111  49.283  40.333  45.420  299216.0  TRBUSDT
1   2020-09-05  45.396  47.066  25.775  30.532  399394.6  TRBUSDT
2   2020-09-06  30.527  39.098  25.582  38.236  588695.6  TRBUSDT
3   2020-09-07  38.204  43.604  29.290  37.776  598177.9  TRBUSDT
4   2020-09-08  37.804  38.380  30.494  32.738  355175.3  TRBUSDT
..         ...     ...     ...     ...     ...       ...      ...
510 2022-01-27  18.950  19.700  17.770  18.640  698048.1  TRBUSDT
511 2022-01-28  18.640  20.100  18.300  20.010  696296.2  TRBUSDT
512 2022-01-29  20.000  21.080  19.880  20.770  495901.2  TRBUSDT
513 2022-01-30  20.770  21.240  19.720  20.050  513184.7  TRBUSDT
514 2022-01-31  20.030  20.560  18.880  20.460  552947.9  TRBUSDT

[515 rows x 7 columns]
processing ONTUSDT.csv (23/145)

h=Int64Index([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=1037755),m=Int64Index([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=1037755),path=testdata/source/1440d/0000/ONTUSDT.csv
sub_df(0)=
                       open   high     low   close     volume   symbol
date
2020-02-11 08:05:00  0.9213  1.066  0.9155  1.0352  8177085.7  ONTUSDT
2020-02-11 08:06:00  0.9320  1.066  0.9155  1.0390  8188230.6  ONTUSDT
2020-02-11 08:07:00  0.9310  1.066  0.9155  1.0442  8235123.9  ONTUSDT
2020-02-11 08:08:00  0.9313  1.066  0.9155  1.0380  8249660.3  ONTUSDT
2020-02-11 08:09:00  0.9326  1.066  0.9155  1.0377  8240972.8  ONTUSDT
...                     ...    ...     ...     ...        ...      ...
2022-01-31 23:55:00  0.4845    NaN     NaN     NaN        NaN  ONTUSDT
2022-01-31 23:56:00  0.4846    NaN     NaN     NaN        NaN  ONTUSDT
2022-01-31 23:57:00  0.4847    NaN     NaN     NaN        NaN  ONTUSDT
2022-01-31 23:58:00  0.4846    NaN     NaN     NaN        NaN  ONTUSDT
2022-01-31 23:59:00  0.4846    NaN     NaN     NaN        NaN  ONTUSDT

[1037755 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close        volume   symbol
0   2020-02-12  0.9775  1.0700  0.9758  1.0367  9.102631e+06  ONTUSDT
1   2020-02-13  1.0377  1.0896  0.9563  1.0247  7.088374e+06  ONTUSDT
2   2020-02-14  1.0252  1.0740  0.9996  1.0733  4.313762e+06  ONTUSDT
3   2020-02-15  1.0732  1.1000  0.9355  0.9606  6.931776e+06  ONTUSDT
4   2020-02-16  0.9603  1.0057  0.8101  0.9042  8.612743e+06  ONTUSDT
..         ...     ...     ...     ...     ...           ...      ...
715 2022-01-27  0.4565  0.4674  0.4347  0.4616  4.647705e+07  ONTUSDT
716 2022-01-28  0.4616  0.4752  0.4494  0.4721  3.232825e+07  ONTUSDT
717 2022-01-29  0.4720  0.4864  0.4701  0.4825  2.301071e+07  ONTUSDT
718 2022-01-30  0.4827  0.5019  0.4641  0.4745  3.302902e+07  ONTUSDT
719 2022-01-31  0.4745  0.4865  0.4525  0.4842  2.698960e+07  ONTUSDT

[720 rows x 7 columns]
processing MANAUSDT.csv (24/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=464700),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=464700),path=testdata/source/1440d/0000/MANAUSDT.csv
sub_df(0)=
                       open    high     low   close      volume    symbol
date
2021-03-15 07:00:00  1.0589  1.2371  0.9284  0.9845  38302145.0  MANAUSDT
2021-03-15 07:01:00  1.0613  1.2371  0.9284  0.9866  38260876.0  MANAUSDT
2021-03-15 07:02:00  1.0601  1.2371  0.9284  0.9920  38237743.0  MANAUSDT
2021-03-15 07:03:00  1.0604  1.2371  0.9284  0.9974  38236781.0  MANAUSDT
2021-03-15 07:04:00  1.0591  1.2371  0.9284  0.9963  38264586.0  MANAUSDT
...                     ...     ...     ...     ...         ...       ...
2022-01-31 23:55:00  2.8149     NaN     NaN     NaN         NaN  MANAUSDT
2022-01-31 23:56:00  2.8250     NaN     NaN     NaN         NaN  MANAUSDT
2022-01-31 23:57:00  2.8249     NaN     NaN     NaN         NaN  MANAUSDT
2022-01-31 23:58:00  2.8218     NaN     NaN     NaN         NaN  MANAUSDT
2022-01-31 23:59:00  2.8149     NaN     NaN     NaN         NaN  MANAUSDT

[464700 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close       volume    symbol
0   2021-03-16  1.0527  1.0786  0.8476  0.9101   33040557.0  MANAUSDT
1   2021-03-17  0.9101  1.0969  0.7761  1.0626  126106481.0  MANAUSDT
2   2021-03-18  1.0625  1.0881  0.9625  0.9816   80594002.0  MANAUSDT
3   2021-03-19  0.9803  1.0300  0.9461  0.9653   35748964.0  MANAUSDT
4   2021-03-20  0.9655  1.0215  0.8856  0.8983   43230685.0  MANAUSDT
..         ...     ...     ...     ...     ...          ...       ...
317 2022-01-27  2.1582  2.3483  2.0284  2.2503  228319729.0  MANAUSDT
318 2022-01-28  2.2496  2.3120  2.1624  2.2779  149508362.0  MANAUSDT
319 2022-01-29  2.2777  2.4169  2.2683  2.3687  111829153.0  MANAUSDT
320 2022-01-30  2.3680  2.5594  2.3519  2.5024  186228219.0  MANAUSDT
321 2022-01-31  2.5025  2.8600  2.3599  2.8179  430432928.0  MANAUSDT

[322 rows x 7 columns]
processing DUSKUSDT.csv (25/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=35790),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=35790),path=testdata/source/1440d/0000/DUSKUSDT.csv
sub_df(0)=
                        open     high      low    close      volume    symbol
date
2022-01-07 03:30:00  0.74780  0.76845  0.68639  0.69455  12867290.0  DUSKUSDT
2022-01-07 03:31:00  0.75040  0.76845  0.68639  0.69454  12864432.0  DUSKUSDT
2022-01-07 03:32:00  0.74052  0.76845  0.68639  0.69221  12857793.0  DUSKUSDT
2022-01-07 03:33:00  0.74796  0.76845  0.68639  0.69179  12847162.0  DUSKUSDT
2022-01-07 03:34:00  0.73888  0.76845  0.68639  0.69417  12841819.0  DUSKUSDT
...                      ...      ...      ...      ...         ...       ...
2022-01-31 23:55:00  0.54050      NaN      NaN      NaN         NaN  DUSKUSDT
2022-01-31 23:56:00  0.54077      NaN      NaN      NaN         NaN  DUSKUSDT
2022-01-31 23:57:00  0.54079      NaN      NaN      NaN         NaN  DUSKUSDT
2022-01-31 23:58:00  0.54112      NaN      NaN      NaN         NaN  DUSKUSDT
2022-01-31 23:59:00  0.54100      NaN      NaN      NaN         NaN  DUSKUSDT

[35790 rows x 6 columns]
sub_df(1)=
         date     open     high      low    close       volume    symbol
0  2022-01-08  0.69812  0.76989  0.59026  0.63383   36823778.0  DUSKUSDT
1  2022-01-09  0.63289  0.69212  0.62291  0.66046   31406941.0  DUSKUSDT
2  2022-01-10  0.66041  0.67179  0.56717  0.60139   31761708.0  DUSKUSDT
3  2022-01-11  0.60152  0.70390  0.55000  0.68209   79190210.0  DUSKUSDT
4  2022-01-12  0.68255  0.75762  0.68003  0.74085  157506346.0  DUSKUSDT
5  2022-01-13  0.74047  0.89948  0.73900  0.83545  351539861.0  DUSKUSDT
6  2022-01-14  0.83548  0.97188  0.81550  0.95935  197607734.0  DUSKUSDT
7  2022-01-15  0.95939  0.96888  0.89112  0.89671  114076253.0  DUSKUSDT
8  2022-01-16  0.89667  1.05555  0.87340  1.02906  219060539.0  DUSKUSDT
9  2022-01-17  1.02900  1.07711  0.92814  0.94260  244635111.0  DUSKUSDT
10 2022-01-18  0.94261  0.97968  0.85200  0.91629  129024876.0  DUSKUSDT
11 2022-01-19  0.91620  0.97415  0.83983  0.84605  100080983.0  DUSKUSDT
12 2022-01-20  0.84559  0.86833  0.74559  0.75771  144548658.0  DUSKUSDT
13 2022-01-21  0.75771  0.77382  0.60350  0.63602  153515063.0  DUSKUSDT
14 2022-01-22  0.63592  0.67200  0.46047  0.54746  166092364.0  DUSKUSDT
15 2022-01-23  0.54788  0.65389  0.53863  0.60821  232045900.0  DUSKUSDT
16 2022-01-24  0.60768  0.60812  0.49656  0.57247  205065343.0  DUSKUSDT
17 2022-01-25  0.57295  0.57700  0.52699  0.55418   81213361.0  DUSKUSDT
18 2022-01-26  0.55421  0.70000  0.53606  0.60321  148536200.0  DUSKUSDT
19 2022-01-27  0.60330  0.69716  0.57599  0.65250  310503956.0  DUSKUSDT
20 2022-01-28  0.65208  0.67934  0.59068  0.62645  121594272.0  DUSKUSDT
21 2022-01-29  0.62678  0.65067  0.59617  0.60166   71881963.0  DUSKUSDT
22 2022-01-30  0.60236  0.60780  0.55500  0.55813   65718253.0  DUSKUSDT
23 2022-01-31  0.55844  0.58880  0.52384  0.54024  142254253.0  DUSKUSDT
processing AVAXUSDT.csv (26/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=713820),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=713820),path=testdata/source/1440d/0000/AVAXUSDT.csv
sub_df(0)=
                        open    high     low   close      volume    symbol
date
2020-09-23 07:00:00   3.9300  4.6092  3.3778  3.6706  17065704.0  AVAXUSDT
2020-09-23 07:01:00   4.3730  4.6092  3.3778  3.6749  17068876.0  AVAXUSDT
2020-09-23 07:02:00   4.2691  4.6092  3.3778  3.6869  17066666.0  AVAXUSDT
2020-09-23 07:03:00   4.3619  4.6092  3.3778  3.7186  17062061.0  AVAXUSDT
2020-09-23 07:04:00   4.3300  4.6092  3.3778  3.7317  17060820.0  AVAXUSDT
...                      ...     ...     ...     ...         ...       ...
2022-01-31 23:55:00  69.7800     NaN     NaN     NaN         NaN  AVAXUSDT
2022-01-31 23:56:00  69.8600     NaN     NaN     NaN         NaN  AVAXUSDT
2022-01-31 23:57:00  69.9700     NaN     NaN     NaN         NaN  AVAXUSDT
2022-01-31 23:58:00  69.9400     NaN     NaN     NaN         NaN  AVAXUSDT
2022-01-31 23:59:00  69.9600     NaN     NaN     NaN         NaN  AVAXUSDT

[713820 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close      volume    symbol
0   2020-09-24   3.5123   4.8600   3.4171   4.6133  12968822.0  AVAXUSDT
1   2020-09-25   4.6129   5.0295   4.1890   4.6867  11945245.0  AVAXUSDT
2   2020-09-26   4.6892   4.8025   4.3459   4.5203   6912586.0  AVAXUSDT
3   2020-09-27   4.5244   4.7000   4.0976   4.6391   5967454.0  AVAXUSDT
4   2020-09-28   4.6383   4.6870   4.1500   4.1955   5522693.0  AVAXUSDT
..         ...      ...      ...      ...      ...         ...       ...
490 2022-01-27  65.8300  67.8700  61.0500  64.6600   7463999.0  AVAXUSDT
491 2022-01-28  64.6300  67.4700  61.6700  66.9300   5282744.0  AVAXUSDT
492 2022-01-29  66.9300  73.6900  66.7900  71.8700   5727988.0  AVAXUSDT
493 2022-01-30  71.8400  72.3300  66.7900  67.9100   4425759.0  AVAXUSDT
494 2022-01-31  67.9000  70.6100  64.2100  69.8200   5340056.0  AVAXUSDT

[495 rows x 7 columns]
processing OMGUSDT.csv (27/145)

h=Int64Index([ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=833218),m=Int64Index([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=833218),path=testdata/source/1440d/0000/OMGUSDT.csv
sub_df(0)=
                       open    high     low   close     volume   symbol
date
2020-07-02 09:02:00  1.3775  1.4721  1.3520  1.4074  4079741.4  OMGUSDT
2020-07-02 09:03:00  1.4321  1.4589  1.3792  1.4068  4047165.4  OMGUSDT
2020-07-02 09:04:00  1.4400  1.4589  1.3792  1.4068  3985398.5  OMGUSDT
2020-07-02 09:05:00  1.4423  1.4589  1.3792  1.4064  3971787.9  OMGUSDT
2020-07-02 09:06:00  1.4385  1.4589  1.3792  1.4064  3945670.9  OMGUSDT
...                     ...     ...     ...     ...        ...      ...
2022-01-31 23:55:00  5.0060     NaN     NaN     NaN        NaN  OMGUSDT
2022-01-31 23:56:00  5.0080     NaN     NaN     NaN        NaN  OMGUSDT
2022-01-31 23:57:00  5.0140     NaN     NaN     NaN        NaN  OMGUSDT
2022-01-31 23:58:00  5.0110     NaN     NaN     NaN        NaN  OMGUSDT
2022-01-31 23:59:00  5.0120     NaN     NaN     NaN        NaN  OMGUSDT

[833218 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close        volume   symbol
0   2020-07-03  1.4162  1.4570  1.3792  1.4297  1.766292e+06  OMGUSDT
1   2020-07-04  1.4296  1.5611  1.4296  1.5190  3.810548e+06  OMGUSDT
2   2020-07-05  1.5180  1.5246  1.4620  1.4990  1.706877e+06  OMGUSDT
3   2020-07-06  1.4990  1.5932  1.4948  1.5693  2.993484e+06  OMGUSDT
4   2020-07-07  1.5695  1.5725  1.5027  1.5285  1.683650e+06  OMGUSDT
..         ...     ...     ...     ...     ...           ...      ...
573 2022-01-27  4.2240  4.4130  4.0100  4.2160  1.188698e+07  OMGUSDT
574 2022-01-28  4.2160  4.6290  4.2000  4.5730  2.375155e+07  OMGUSDT
575 2022-01-29  4.5720  4.9280  4.5430  4.8690  1.584728e+07  OMGUSDT
576 2022-01-30  4.8670  4.9990  4.6620  4.8350  1.262717e+07  OMGUSDT
577 2022-01-31  4.8340  5.1430  4.5250  5.0130  1.779377e+07  OMGUSDT

[578 rows x 7 columns]
processing OGNUSDT.csv (28/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=440220),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=440220),path=testdata/source/1440d/0000/OGNUSDT.csv
sub_df(0)=
                       open    high     low   close     volume   symbol
date
2021-04-01 07:00:00  2.0000  2.0000  1.7341  1.8260  7477540.0  OGNUSDT
2021-04-01 07:01:00  1.8769  1.9125  1.7341  1.8240  7456750.0  OGNUSDT
2021-04-01 07:02:00  1.8850  1.9125  1.7341  1.8246  7449231.0  OGNUSDT
2021-04-01 07:03:00  1.9023  1.9108  1.7341  1.8225  7422469.0  OGNUSDT
2021-04-01 07:04:00  1.8837  1.9108  1.7341  1.8229  7404312.0  OGNUSDT
...                     ...     ...     ...     ...        ...      ...
2022-01-31 23:55:00  0.3172     NaN     NaN     NaN        NaN  OGNUSDT
2022-01-31 23:56:00  0.3171     NaN     NaN     NaN        NaN  OGNUSDT
2022-01-31 23:57:00  0.3174     NaN     NaN     NaN        NaN  OGNUSDT
2022-01-31 23:58:00  0.3173     NaN     NaN     NaN        NaN  OGNUSDT
2022-01-31 23:59:00  0.3174     NaN     NaN     NaN        NaN  OGNUSDT

[440220 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume   symbol
0   2021-04-02  1.7905  2.0525  1.7568  1.8447   8667178.0  OGNUSDT
1   2021-04-03  1.8447  1.8986  1.6610  1.6680   8029302.0  OGNUSDT
2   2021-04-04  1.6680  1.9983  1.6500  1.9688   9330381.0  OGNUSDT
3   2021-04-05  1.9684  2.8464  1.8350  2.5222  21791244.0  OGNUSDT
4   2021-04-06  2.5222  3.2141  2.3200  2.3230  56108611.0  OGNUSDT
..         ...     ...     ...     ...     ...         ...      ...
300 2022-01-27  0.3221  0.3305  0.2971  0.3130  59989849.0  OGNUSDT
301 2022-01-28  0.3132  0.3289  0.2985  0.3273  50745665.0  OGNUSDT
302 2022-01-29  0.3273  0.3413  0.3232  0.3327  58876966.0  OGNUSDT
303 2022-01-30  0.3327  0.3387  0.3087  0.3123  60587193.0  OGNUSDT
304 2022-01-31  0.3123  0.3187  0.2976  0.3169  57035965.0  OGNUSDT

[305 rows x 7 columns]
processing RVNUSDT.csv (29/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=493500),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=493500),path=testdata/source/1440d/0000/RVNUSDT.csv
sub_df(0)=
                        open   high      low    close       volume   symbol
date
2021-02-23 07:00:00  0.16660  0.199  0.13257  0.18453  144827539.0  RVNUSDT
2021-02-23 07:01:00  0.17100  0.199  0.13257  0.18467  144612685.0  RVNUSDT
2021-02-23 07:02:00  0.17090  0.199  0.13257  0.18301  144559093.0  RVNUSDT
2021-02-23 07:03:00  0.17308  0.199  0.13257  0.18307  144450245.0  RVNUSDT
2021-02-23 07:04:00  0.17331  0.199  0.13257  0.18343  144424110.0  RVNUSDT
...                      ...    ...      ...      ...          ...      ...
2022-01-31 23:55:00  0.07009    NaN      NaN      NaN          NaN  RVNUSDT
2022-01-31 23:56:00  0.07010    NaN      NaN      NaN          NaN  RVNUSDT
2022-01-31 23:57:00  0.07016    NaN      NaN      NaN          NaN  RVNUSDT
2022-01-31 23:58:00  0.07014    NaN      NaN      NaN          NaN  RVNUSDT
2022-01-31 23:59:00  0.07011    NaN      NaN      NaN          NaN  RVNUSDT

[493500 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close       volume   symbol
0   2021-02-24  0.18023  0.19900  0.16504  0.18174   60419538.0  RVNUSDT
1   2021-02-25  0.18190  0.19140  0.16000  0.16296   38587384.0  RVNUSDT
2   2021-02-26  0.16299  0.17205  0.14758  0.15511   28550048.0  RVNUSDT
3   2021-02-27  0.15511  0.16200  0.13560  0.14213   56118596.0  RVNUSDT
4   2021-02-28  0.14217  0.14221  0.11600  0.13111  160578453.0  RVNUSDT
..         ...      ...      ...      ...      ...          ...      ...
337 2022-01-27  0.06541  0.06696  0.06100  0.06484  293632765.0  RVNUSDT
338 2022-01-28  0.06484  0.07049  0.06456  0.06952  493967697.0  RVNUSDT
339 2022-01-29  0.06952  0.07449  0.06940  0.07119  576315869.0  RVNUSDT
340 2022-01-30  0.07120  0.07190  0.06731  0.06877  232638584.0  RVNUSDT
341 2022-01-31  0.06874  0.07056  0.06510  0.07005  287906224.0  RVNUSDT

[342 rows x 7 columns]
processing DASHUSDT.csv (30/145)
h=Int64Index([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=1047834),m=Int64Index([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=1047834),path=testdata/source/1440d/0000/DASHUSDT.csv
sub_df(0)=
                       open    high     low   close     volume    symbol
date
2020-02-04 08:06:00  115.50  115.50  108.47  114.32  42399.014  DASHUSDT
2020-02-04 08:07:00  114.99  115.36  108.47  114.36  42309.234  DASHUSDT
2020-02-04 08:08:00  114.95  115.36  108.47  114.21  42380.858  DASHUSDT
2020-02-04 08:09:00  114.92  115.36  108.47  114.15  42382.531  DASHUSDT
2020-02-04 08:10:00  114.92  115.36  108.47  114.32  42440.444  DASHUSDT
...                     ...     ...     ...     ...        ...       ...
2022-01-31 23:55:00   94.22     NaN     NaN     NaN        NaN  DASHUSDT
2022-01-31 23:56:00   94.26     NaN     NaN     NaN        NaN  DASHUSDT
2022-01-31 23:57:00   94.38     NaN     NaN     NaN        NaN  DASHUSDT
2022-01-31 23:58:00   94.35     NaN     NaN     NaN        NaN  DASHUSDT
2022-01-31 23:59:00   94.30     NaN     NaN     NaN        NaN  DASHUSDT

[1047834 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume    symbol
0   2020-02-05  111.29  124.76  110.04  122.94  108596.428  DASHUSDT
1   2020-02-06  123.09  125.36  117.15  120.87   52416.412  DASHUSDT
2   2020-02-07  120.84  123.38  118.26  118.88   50706.740  DASHUSDT
3   2020-02-08  118.88  132.32  113.16  126.64  150490.454  DASHUSDT
4   2020-02-09  126.56  131.41  124.00  128.67   58992.758  DASHUSDT
..         ...     ...     ...     ...     ...         ...       ...
722 2022-01-27   92.99   94.07   87.10   91.61  551769.994  DASHUSDT
723 2022-01-28   91.61   95.99   89.66   95.43  407421.778  DASHUSDT
724 2022-01-29   95.41   97.84   93.19   96.52  267005.392  DASHUSDT
725 2022-01-30   96.51   98.09   91.88   92.69  277304.005  DASHUSDT
726 2022-01-31   92.66   94.95   88.20   94.10  292730.329  DASHUSDT

[727 rows x 7 columns]
processing LINKUSDT.csv (31/145)

h=Int64Index([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=1073760),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=1073760),path=testdata/source/1440d/0000/LINKUSDT.csv
sub_df(0)=
                       open   high   low  close       volume    symbol
date
2020-01-17 08:00:00   2.669  2.896  2.56  2.635  11155355.70  LINKUSDT
2020-01-17 08:01:00   2.670  2.896  2.56  2.640  11153805.72  LINKUSDT
2020-01-17 08:02:00   2.670  2.896  2.56  2.639  11156687.13  LINKUSDT
2020-01-17 08:03:00   2.670  2.896  2.56  2.640  11149849.87  LINKUSDT
2020-01-17 08:04:00   2.670  2.896  2.56  2.635  11147250.22  LINKUSDT
...                     ...    ...   ...    ...          ...       ...
2022-01-31 23:55:00  17.235    NaN   NaN    NaN          NaN  LINKUSDT
2022-01-31 23:56:00  17.238    NaN   NaN    NaN          NaN  LINKUSDT
2022-01-31 23:57:00  17.232    NaN   NaN    NaN          NaN  LINKUSDT
2022-01-31 23:58:00  17.221    NaN   NaN    NaN          NaN  LINKUSDT
2022-01-31 23:59:00  17.204    NaN   NaN    NaN          NaN  LINKUSDT

[1073760 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close        volume    symbol
0   2020-01-18   2.696   2.799   2.560   2.774  7.920982e+06  LINKUSDT
1   2020-01-19   2.777   2.854   2.519   2.623  9.414962e+06  LINKUSDT
2   2020-01-20   2.623   2.745   2.544   2.695  7.244722e+06  LINKUSDT
3   2020-01-21   2.694   2.745   2.561   2.673  5.857502e+06  LINKUSDT
4   2020-01-22   2.675   2.694   2.626   2.654  3.308776e+06  LINKUSDT
..         ...     ...     ...     ...     ...           ...       ...
740 2022-01-27  15.222  15.700  14.281  15.209  2.792991e+07  LINKUSDT
741 2022-01-28  15.208  16.275  14.719  16.133  2.377971e+07  LINKUSDT
742 2022-01-29  16.132  16.750  15.948  16.217  1.776692e+07  LINKUSDT
743 2022-01-30  16.217  18.121  16.004  17.754  3.152683e+07  LINKUSDT
744 2022-01-31  17.752  17.875  16.429  17.143  3.158385e+07  LINKUSDT

[745 rows x 7 columns]
processing NUUSDT.csv (32/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=148110),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=148110),path=testdata/source/1440d/0000/NUUSDT.csv
sub_df(0)=
                       open    high     low   close      volume  symbol
date
2021-10-21 03:30:00  1.1617  1.2454  1.1070  1.1550  40481182.5  NUUSDT
2021-10-21 03:31:00  1.1610  1.2454  1.1199  1.1563  40055057.5  NUUSDT
2021-10-21 03:32:00  1.1625  1.2454  1.1199  1.1567  39634219.0  NUUSDT
2021-10-21 03:33:00  1.1690  1.2454  1.1199  1.1565  39197510.3  NUUSDT
2021-10-21 03:34:00  1.1670  1.2454  1.1199  1.1565  38885029.4  NUUSDT
...                     ...     ...     ...     ...         ...     ...
2022-01-31 23:55:00  0.4952     NaN     NaN     NaN         NaN  NUUSDT
2022-01-31 23:56:00  0.4954     NaN     NaN     NaN         NaN  NUUSDT
2022-01-31 23:57:00  0.4957     NaN     NaN     NaN         NaN  NUUSDT
2022-01-31 23:58:00  0.4953     NaN     NaN     NaN         NaN  NUUSDT
2022-01-31 23:59:00  0.4951     NaN     NaN     NaN         NaN  NUUSDT

[148110 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close        volume  symbol
0   2021-10-22  1.1507  1.1829  1.0875  1.1262  1.512126e+07  NUUSDT
1   2021-10-23  1.1266  1.1835  1.1078  1.1544  1.931267e+07  NUUSDT
2   2021-10-24  1.1542  1.1583  1.0729  1.1039  9.571585e+06  NUUSDT
3   2021-10-25  1.1041  1.1283  1.0854  1.1193  1.142938e+07  NUUSDT
4   2021-10-26  1.1197  1.1539  1.0930  1.1114  3.532401e+07  NUUSDT
..         ...     ...     ...     ...     ...           ...     ...
97  2022-01-27  0.4455  0.4592  0.4251  0.4501  3.272155e+07  NUUSDT
98  2022-01-28  0.4500  0.4814  0.4398  0.4768  8.477138e+07  NUUSDT
99  2022-01-29  0.4767  0.5290  0.4760  0.5115  1.973346e+08  NUUSDT
100 2022-01-30  0.5116  0.5188  0.4836  0.4918  5.945638e+07  NUUSDT
101 2022-01-31  0.4917  0.4964  0.4614  0.4953  3.719144e+07  NUUSDT

[102 rows x 7 columns]
processing ZRXUSDT.csv (33/145)
h=Int64Index([ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=844738),m=Int64Index([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=844738),path=testdata/source/1440d/0000/ZRXUSDT.csv
sub_df(0)=
                       open    high     low   close     volume   symbol
date
2020-06-24 09:02:00  0.3620  0.3620  0.3308  0.3432  7041104.9  ZRXUSDT
2020-06-24 09:03:00  0.3526  0.3559  0.3308  0.3432  6991776.3  ZRXUSDT
2020-06-24 09:04:00  0.3540  0.3559  0.3308  0.3432  6941921.0  ZRXUSDT
2020-06-24 09:05:00  0.3559  0.3559  0.3308  0.3429  6904289.7  ZRXUSDT
2020-06-24 09:06:00  0.3544  0.3547  0.3308  0.3428  6872114.6  ZRXUSDT
...                     ...     ...     ...     ...        ...      ...
2022-01-31 23:55:00  0.5671     NaN     NaN     NaN        NaN  ZRXUSDT
2022-01-31 23:56:00  0.5676     NaN     NaN     NaN        NaN  ZRXUSDT
2022-01-31 23:57:00  0.5672     NaN     NaN     NaN        NaN  ZRXUSDT
2022-01-31 23:58:00  0.5674     NaN     NaN     NaN        NaN  ZRXUSDT
2022-01-31 23:59:00  0.5675     NaN     NaN     NaN        NaN  ZRXUSDT

[844738 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close        volume   symbol
0   2020-06-25  0.3432  0.3470  0.3308  0.3353  2.449884e+06  ZRXUSDT
1   2020-06-26  0.3353  0.3619  0.3334  0.3528  1.515148e+07  ZRXUSDT
2   2020-06-27  0.3528  0.3674  0.3076  0.3325  1.355112e+07  ZRXUSDT
3   2020-06-28  0.3325  0.3419  0.3205  0.3309  4.393498e+06  ZRXUSDT
4   2020-06-29  0.3309  0.3455  0.3265  0.3452  2.990623e+06  ZRXUSDT
..         ...     ...     ...     ...     ...           ...      ...
581 2022-01-27  0.5304  0.5600  0.4997  0.5288  5.770115e+07  ZRXUSDT
582 2022-01-28  0.5285  0.5479  0.5073  0.5437  2.605916e+07  ZRXUSDT
583 2022-01-29  0.5435  0.5715  0.5413  0.5652  1.570612e+07  ZRXUSDT
584 2022-01-30  0.5652  0.5784  0.5375  0.5525  1.988685e+07  ZRXUSDT
585 2022-01-31  0.5522  0.5680  0.5218  0.5663  1.943972e+07  ZRXUSDT

[586 rows x 7 columns]
processing HNTUSDT.csv (34/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=706620),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=706620),path=testdata/source/1440d/0000/HNTUSDT.csv
sub_df(0)=
                        open   high     low   close      volume   symbol
date
2020-09-28 07:00:00   1.5600  1.989  1.5408  1.6558  11559055.0  HNTUSDT
2020-09-28 07:01:00   1.6801  1.989  1.5408  1.6541  11524181.0  HNTUSDT
2020-09-28 07:02:00   1.6939  1.989  1.5408  1.6467  11513927.0  HNTUSDT
2020-09-28 07:03:00   1.7550  1.989  1.5408  1.6464  11426681.0  HNTUSDT
2020-09-28 07:04:00   1.7634  1.989  1.5408  1.6449  11359665.0  HNTUSDT
...                      ...    ...     ...     ...         ...      ...
2022-01-31 23:55:00  27.7810    NaN     NaN     NaN         NaN  HNTUSDT
2022-01-31 23:56:00  27.7990    NaN     NaN     NaN         NaN  HNTUSDT
2022-01-31 23:57:00  27.8320    NaN     NaN     NaN         NaN  HNTUSDT
2022-01-31 23:58:00  27.8160    NaN     NaN     NaN         NaN  HNTUSDT
2022-01-31 23:59:00  27.8230    NaN     NaN     NaN         NaN  HNTUSDT

[706620 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close     volume   symbol
0   2020-09-29   1.6480   1.7241   1.4828   1.6369  2632654.0  HNTUSDT
1   2020-09-30   1.6350   1.6372   1.5096   1.5703  1289511.0  HNTUSDT
2   2020-10-01   1.5703   1.7446   1.4689   1.5409  1875898.0  HNTUSDT
3   2020-10-02   1.5394   1.5394   1.4500   1.5192  1083092.0  HNTUSDT
4   2020-10-03   1.5165   1.5922   1.4400   1.4527   841397.0  HNTUSDT
..         ...      ...      ...      ...      ...        ...      ...
485 2022-01-27  29.0880  29.8160  26.7170  28.1970  5694298.0  HNTUSDT
486 2022-01-28  28.2110  28.8660  26.2150  26.6460  3203874.0  HNTUSDT
487 2022-01-29  26.6390  28.1450  26.2490  26.9750  2531201.0  HNTUSDT
488 2022-01-30  26.9780  29.5880  26.5720  28.9170  2371341.0  HNTUSDT
489 2022-01-31  28.9010  28.9710  26.6470  27.7730  2147432.0  HNTUSDT

[490 rows x 7 columns]
processing CVCUSDT.csv (35/145)

h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=643260),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=643260),path=testdata/source/1440d/0000/CVCUSDT.csv
sub_df(0)=
                        open    high      low    close       volume   symbol
date
2020-11-11 07:00:00  0.10801  0.1195  0.08201  0.08742  315280781.0  CVCUSDT
2020-11-11 07:01:00  0.10897  0.1195  0.08201  0.08727  313929954.0  CVCUSDT
2020-11-11 07:02:00  0.10860  0.1195  0.08201  0.08776  312229936.0  CVCUSDT
2020-11-11 07:03:00  0.10481  0.1195  0.08201  0.08758  310802104.0  CVCUSDT
2020-11-11 07:04:00  0.10490  0.1195  0.08201  0.08684  308510849.0  CVCUSDT
...                      ...     ...      ...      ...          ...      ...
2022-01-31 23:55:00  0.27010     NaN      NaN      NaN          NaN  CVCUSDT
2022-01-31 23:56:00  0.27022     NaN      NaN      NaN          NaN  CVCUSDT
2022-01-31 23:57:00  0.27088     NaN      NaN      NaN          NaN  CVCUSDT
2022-01-31 23:58:00  0.27077     NaN      NaN      NaN          NaN  CVCUSDT
2022-01-31 23:59:00  0.27071     NaN      NaN      NaN          NaN  CVCUSDT

[643260 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close       volume   symbol
0   2020-11-12  0.09398  0.10360  0.08201  0.09872  331337766.0  CVCUSDT
1   2020-11-13  0.09872  0.12636  0.09602  0.10685  692496048.0  CVCUSDT
2   2020-11-14  0.10686  0.11835  0.09864  0.10962  306048070.0  CVCUSDT
3   2020-11-15  0.10949  0.11900  0.10165  0.10735  216889917.0  CVCUSDT
4   2020-11-16  0.10736  0.10754  0.09977  0.10099  108453178.0  CVCUSDT
..         ...      ...      ...      ...      ...          ...      ...
441 2022-01-27  0.22413  0.25548  0.21600  0.23558  363468090.0  CVCUSDT
442 2022-01-28  0.23562  0.25310  0.23149  0.25190  169761893.0  CVCUSDT
443 2022-01-29  0.25178  0.27034  0.25109  0.26657  157567310.0  CVCUSDT
444 2022-01-30  0.26655  0.26932  0.25248  0.25624   83394415.0  CVCUSDT
445 2022-01-31  0.25624  0.27122  0.24240  0.27043  112707882.0  CVCUSDT

[446 rows x 7 columns]
processing HOTUSDT.csv (36/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=443100),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=443100),path=testdata/source/1440d/0000/HOTUSDT.csv
sub_df(0)=
                         open      high       low     close        volume  \
date
2021-03-30 07:00:00  0.015000  0.020777  0.014858  0.017625  2.003330e+10
2021-03-30 07:01:00  0.016281  0.020777  0.014858  0.017574  2.003402e+10
2021-03-30 07:02:00  0.015897  0.020777  0.014858  0.017503  2.004345e+10
2021-03-30 07:03:00  0.015900  0.020777  0.014858  0.017538  2.004647e+10
2021-03-30 07:04:00  0.015831  0.020777  0.014858  0.017247  2.008804e+10
...                       ...       ...       ...       ...           ...
2022-01-31 23:55:00  0.004531       NaN       NaN       NaN           NaN
2022-01-31 23:56:00  0.004531       NaN       NaN       NaN           NaN
2022-01-31 23:57:00  0.004537       NaN       NaN       NaN           NaN
2022-01-31 23:58:00  0.004535       NaN       NaN       NaN           NaN
2022-01-31 23:59:00  0.004534       NaN       NaN       NaN           NaN

                      symbol
date
2021-03-30 07:00:00  HOTUSDT
2021-03-30 07:01:00  HOTUSDT
2021-03-30 07:02:00  HOTUSDT
2021-03-30 07:03:00  HOTUSDT
2021-03-30 07:04:00  HOTUSDT
...                      ...
2022-01-31 23:55:00  HOTUSDT
2022-01-31 23:56:00  HOTUSDT
2022-01-31 23:57:00  HOTUSDT
2022-01-31 23:58:00  HOTUSDT
2022-01-31 23:59:00  HOTUSDT

[443100 rows x 6 columns]
sub_df(1)=
          date      open      high       low     close        volume   symbol
0   2021-03-31  0.018176  0.019600  0.015099  0.016786  1.581899e+10  HOTUSDT
1   2021-04-01  0.016785  0.018400  0.016543  0.017400  4.899551e+09  HOTUSDT
2   2021-04-02  0.017413  0.024578  0.017100  0.024317  1.795794e+10  HOTUSDT
3   2021-04-03  0.024317  0.028244  0.021708  0.023090  3.109064e+10  HOTUSDT
4   2021-04-04  0.023080  0.029891  0.022500  0.027283  2.214513e+10  HOTUSDT
..         ...       ...       ...       ...       ...           ...      ...
302 2022-01-27  0.004473  0.004531  0.004210  0.004375  8.570293e+09  HOTUSDT
303 2022-01-28  0.004373  0.004512  0.004225  0.004469  6.572482e+09  HOTUSDT
304 2022-01-29  0.004468  0.004670  0.004458  0.004597  6.791970e+09  HOTUSDT
305 2022-01-30  0.004595  0.004669  0.004387  0.004440  6.617324e+09  HOTUSDT
306 2022-01-31  0.004440  0.004568  0.004263  0.004526  5.755296e+09  HOTUSDT

[307 rows x 7 columns]
processing SOLUSDT.csv (37/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=726780),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=726780),path=testdata/source/1440d/0000/SOLUSDT.csv
sub_df(0)=
                        open   high     low   close     volume   symbol
date
2020-09-14 07:00:00   3.2002  4.910  3.1993  3.2337  5922054.0  SOLUSDT
2020-09-14 07:01:00   3.2731  3.565  3.1993  3.2353  5912669.0  SOLUSDT
2020-09-14 07:02:00   3.3193  3.565  3.1993  3.2298  5903398.0  SOLUSDT
2020-09-14 07:03:00   3.3318  3.565  3.1993  3.2412  5898507.0  SOLUSDT
2020-09-14 07:04:00   3.3151  3.565  3.1993  3.2359  5897591.0  SOLUSDT
...                      ...    ...     ...     ...        ...      ...
2022-01-31 23:55:00  99.6000    NaN     NaN     NaN        NaN  SOLUSDT
2022-01-31 23:56:00  99.6000    NaN     NaN     NaN        NaN  SOLUSDT
2022-01-31 23:57:00  99.7100    NaN     NaN     NaN        NaN  SOLUSDT
2022-01-31 23:58:00  99.7100    NaN     NaN     NaN        NaN  SOLUSDT
2022-01-31 23:59:00  99.7000    NaN     NaN     NaN        NaN  SOLUSDT

[726780 rows x 6 columns]
sub_df(1)=
          date     open      high      low    close      volume   symbol
0   2020-09-15   3.2629    3.3258   2.9001   2.9332   4318305.0  SOLUSDT
1   2020-09-16   2.9299    2.9299   2.4316   2.5395   5698128.0  SOLUSDT
2   2020-09-17   2.5400    2.9360   2.3569   2.8855   6499338.0  SOLUSDT
3   2020-09-18   2.8821    3.1500   2.7240   3.1080   6310796.0  SOLUSDT
4   2020-09-19   3.1080    3.2509   2.9550   3.0193   5004414.0  SOLUSDT
..         ...      ...       ...      ...      ...         ...      ...
499 2022-01-27  92.0400   94.6300  85.6000  89.4300  15044776.0  SOLUSDT
500 2022-01-28  89.4300   93.4800  87.1000  91.2900  11397177.0  SOLUSDT
501 2022-01-29  91.2900   98.8800  90.4000  96.1100   8792459.0  SOLUSDT
502 2022-01-30  96.0800   97.6400  91.3100  93.1500   5528616.0  SOLUSDT
503 2022-01-31  93.1600  101.2900  89.1500  99.4800   9829327.0  SOLUSDT

[504 rows x 7 columns]
processing BTSUSDT.csv (38/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=525180),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=525180),path=testdata/source/1440d/0000/BTSUSDT.csv
sub_df(0)=
                        open     high     low    close       volume   symbol
date
2021-02-01 07:00:00  0.03610  0.04688  0.0361  0.03776  201797779.0  BTSUSDT
2021-02-01 07:01:00  0.03916  0.04688  0.0365  0.03771  201418228.0  BTSUSDT
2021-02-01 07:02:00  0.03860  0.04688  0.0365  0.03776  201348688.0  BTSUSDT
2021-02-01 07:03:00  0.03894  0.04688  0.0365  0.03775  200651205.0  BTSUSDT
2021-02-01 07:04:00  0.03900  0.04688  0.0365  0.03778  200648210.0  BTSUSDT
...                      ...      ...     ...      ...          ...      ...
2022-01-31 23:55:00  0.02397      NaN     NaN      NaN          NaN  BTSUSDT
2022-01-31 23:56:00  0.02397      NaN     NaN      NaN          NaN  BTSUSDT
2022-01-31 23:57:00  0.02399      NaN     NaN      NaN          NaN  BTSUSDT
2022-01-31 23:58:00  0.02398      NaN     NaN      NaN          NaN  BTSUSDT
2022-01-31 23:59:00  0.02398      NaN     NaN      NaN          NaN  BTSUSDT

[525180 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close       volume   symbol
0   2021-02-02  0.04000  0.04369  0.03531  0.03971  221531092.0  BTSUSDT
1   2021-02-03  0.03971  0.04431  0.03971  0.04202  114061872.0  BTSUSDT
2   2021-02-04  0.04203  0.04800  0.04002  0.04354  178231780.0  BTSUSDT
3   2021-02-05  0.04354  0.04811  0.04256  0.04711  151277972.0  BTSUSDT
4   2021-02-06  0.04711  0.04745  0.04077  0.04320  109784385.0  BTSUSDT
..         ...      ...      ...      ...      ...          ...      ...
359 2022-01-27  0.02295  0.02439  0.02179  0.02333  684028947.0  BTSUSDT
360 2022-01-28  0.02334  0.02415  0.02270  0.02399  375908425.0  BTSUSDT
361 2022-01-29  0.02399  0.02454  0.02354  0.02424  323328642.0  BTSUSDT
362 2022-01-30  0.02424  0.02455  0.02338  0.02394  293331777.0  BTSUSDT
363 2022-01-31  0.02395  0.02413  0.02236  0.02394  426236157.0  BTSUSDT

[364 rows x 7 columns]
processing CELOUSDT.csv (39/145)

h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=182670),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=182670),path=testdata/source/1440d/0000/CELOUSDT.csv
sub_df(0)=
                      open   high   low  close     volume    symbol
date
2021-09-27 03:30:00  6.798  6.863  5.95  6.150  3296644.4  CELOUSDT
2021-09-27 03:31:00  6.679  6.863  5.95  6.144  3263458.8  CELOUSDT
2021-09-27 03:32:00  6.742  6.863  5.95  6.140  3244348.4  CELOUSDT
2021-09-27 03:33:00  6.692  6.863  5.95  6.150  3229173.1  CELOUSDT
2021-09-27 03:34:00  6.664  6.863  5.95  6.144  3219707.0  CELOUSDT
...                    ...    ...   ...    ...        ...       ...
2022-01-31 23:55:00  3.169    NaN   NaN    NaN        NaN  CELOUSDT
2022-01-31 23:56:00  3.169    NaN   NaN    NaN        NaN  CELOUSDT
2022-01-31 23:57:00  3.171    NaN   NaN    NaN        NaN  CELOUSDT
2022-01-31 23:58:00  3.168    NaN   NaN    NaN        NaN  CELOUSDT
2022-01-31 23:59:00  3.168    NaN   NaN    NaN        NaN  CELOUSDT

[182670 rows x 6 columns]
sub_df(1)=
          date   open   high    low  close     volume    symbol
0   2021-09-28  6.139  6.272  5.794  5.819  2158778.8  CELOUSDT
1   2021-09-29  5.819  6.175  5.507  5.700  3021144.6  CELOUSDT
2   2021-09-30  5.698  5.878  5.550  5.646  3194712.1  CELOUSDT
3   2021-10-01  5.653  6.327  5.612  6.164  4502184.3  CELOUSDT
4   2021-10-02  6.164  6.640  6.020  6.292  4080925.7  CELOUSDT
..         ...    ...    ...    ...    ...        ...       ...
121 2022-01-27  3.057  3.171  2.942  3.069  8617673.3  CELOUSDT
122 2022-01-28  3.069  3.151  3.015  3.134  5752988.2  CELOUSDT
123 2022-01-29  3.135  3.202  3.062  3.137  5563463.4  CELOUSDT
124 2022-01-30  3.139  3.193  2.973  3.022  5001599.2  CELOUSDT
125 2022-01-31  3.022  3.180  2.902  3.163  6389481.8  CELOUSDT

[126 rows x 7 columns]
processing DYDXUSDT.csv (40/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=207150),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=207150),path=testdata/source/1440d/0000/DYDXUSDT.csv
sub_df(0)=
                       open   high    low   close      volume    symbol
date
2021-09-10 03:30:00  13.273  13.71  9.815  10.790  16477188.6  DYDXUSDT
2021-09-10 03:31:00  12.960  13.71  9.815  10.768  16539682.5  DYDXUSDT
2021-09-10 03:32:00  13.001  13.71  9.815  10.758  16552780.3  DYDXUSDT
2021-09-10 03:33:00  13.139  13.71  9.815  10.746  16537920.9  DYDXUSDT
2021-09-10 03:34:00  13.133  13.71  9.815  10.790  16524264.1  DYDXUSDT
...                     ...    ...    ...     ...         ...       ...
2022-01-31 23:55:00   5.906    NaN    NaN     NaN         NaN  DYDXUSDT
2022-01-31 23:56:00   5.914    NaN    NaN     NaN         NaN  DYDXUSDT
2022-01-31 23:57:00   5.920    NaN    NaN     NaN         NaN  DYDXUSDT
2022-01-31 23:58:00   5.919    NaN    NaN     NaN         NaN  DYDXUSDT
2022-01-31 23:59:00   5.914    NaN    NaN     NaN         NaN  DYDXUSDT

[207150 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close        volume    symbol
0   2021-09-11  10.429  12.786  10.302  10.947  1.481901e+07  DYDXUSDT
1   2021-09-12  10.947  12.750  10.677  11.304  1.114917e+07  DYDXUSDT
2   2021-09-13  11.300  11.491   9.000  10.415  1.675976e+07  DYDXUSDT
3   2021-09-14  10.427  12.217  10.000  11.692  1.316673e+07  DYDXUSDT
4   2021-09-15  11.711  12.503  11.013  11.613  1.085137e+07  DYDXUSDT
..         ...     ...     ...     ...     ...           ...       ...
138 2022-01-27   5.814   5.959   5.450   5.711  2.891061e+07  DYDXUSDT
139 2022-01-28   5.710   6.063   5.508   5.939  2.457249e+07  DYDXUSDT
140 2022-01-29   5.940   6.160   5.871   6.119  1.648959e+07  DYDXUSDT
141 2022-01-30   6.117   6.234   5.699   5.769  1.612616e+07  DYDXUSDT
142 2022-01-31   5.767   6.022   5.501   5.907  2.084921e+07  DYDXUSDT

[143 rows x 7 columns]
processing GRTUSDT.csv (41/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=588540),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=588540),path=testdata/source/1440d/0000/GRTUSDT.csv
sub_df(0)=
                        open     high      low    close        volume   symbol
date
2020-12-19 07:00:00  0.28916  0.58271  0.28916  0.57383  1.216123e+09  GRTUSDT
2020-12-19 07:01:00  0.30619  0.58271  0.30229  0.57915  1.216590e+09  GRTUSDT
2020-12-19 07:02:00  0.31328  0.58271  0.30229  0.57555  1.216035e+09  GRTUSDT
2020-12-19 07:03:00  0.30690  0.58271  0.30229  0.57651  1.215086e+09  GRTUSDT
2020-12-19 07:04:00  0.30936  0.59200  0.30229  0.58615  1.216636e+09  GRTUSDT
...                      ...      ...      ...      ...           ...      ...
2022-01-31 23:55:00  0.40958      NaN      NaN      NaN           NaN  GRTUSDT
2022-01-31 23:56:00  0.40956      NaN      NaN      NaN           NaN  GRTUSDT
2022-01-31 23:57:00  0.40953      NaN      NaN      NaN           NaN  GRTUSDT
2022-01-31 23:58:00  0.40911      NaN      NaN      NaN           NaN  GRTUSDT
2022-01-31 23:59:00  0.40881      NaN      NaN      NaN           NaN  GRTUSDT

[588540 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close        volume   symbol
0   2020-12-20  0.46610  0.79146  0.44123  0.73419  1.229631e+09  GRTUSDT
1   2020-12-21  0.73309  0.77067  0.45193  0.47201  9.090759e+08  GRTUSDT
2   2020-12-22  0.47230  0.62355  0.42403  0.54615  8.217116e+08  GRTUSDT
3   2020-12-23  0.54584  0.58042  0.34686  0.41205  5.583072e+08  GRTUSDT
4   2020-12-24  0.41211  0.45550  0.35145  0.41101  3.851250e+08  GRTUSDT
..         ...      ...      ...      ...      ...           ...      ...
403 2022-01-27  0.40431  0.41095  0.38335  0.40455  9.008933e+07  GRTUSDT
404 2022-01-28  0.40456  0.41710  0.39473  0.41379  8.247077e+07  GRTUSDT
405 2022-01-29  0.41386  0.42389  0.40532  0.40973  5.752424e+07  GRTUSDT
406 2022-01-30  0.40987  0.42100  0.39525  0.39895  5.698030e+07  GRTUSDT
407 2022-01-31  0.39891  0.41049  0.37861  0.40836  6.583228e+07  GRTUSDT

[408 rows x 7 columns]
processing ZECUSDT.csv (42/145)
h=Int64Index([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=1046399),m=Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=1046399),path=testdata/source/1440d/0000/ZECUSDT.csv
sub_df(0)=
                      open   high    low  close      volume   symbol
date
2020-02-05 08:01:00  65.99  73.47  64.77  71.89  103832.081  ZECUSDT
2020-02-05 08:02:00  65.35  73.47  65.05  71.91  103856.156  ZECUSDT
2020-02-05 08:03:00  65.50  73.47  65.05  71.91  103870.587  ZECUSDT
2020-02-05 08:04:00  65.68  73.47  65.05  71.96  103512.711  ZECUSDT
2020-02-05 08:05:00  65.51  73.47  65.05  71.93  103410.009  ZECUSDT
...                    ...    ...    ...    ...         ...      ...
2022-01-31 23:55:00  94.64    NaN    NaN    NaN         NaN  ZECUSDT
2022-01-31 23:56:00  94.52    NaN    NaN    NaN         NaN  ZECUSDT
2022-01-31 23:57:00  94.58    NaN    NaN    NaN         NaN  ZECUSDT
2022-01-31 23:58:00  94.56    NaN    NaN    NaN         NaN  ZECUSDT
2022-01-31 23:59:00  94.52    NaN    NaN    NaN         NaN  ZECUSDT

[1046399 rows x 6 columns]
sub_df(1)=
          date   open   high    low  close      volume   symbol
0   2020-02-06  71.22  73.47  67.76  70.17   69289.160  ZECUSDT
1   2020-02-07  70.21  72.25  68.03  68.59   98172.843  ZECUSDT
2   2020-02-08  68.61  72.34  66.00  70.13   89554.027  ZECUSDT
3   2020-02-09  70.14  73.10  68.85  71.43   73579.213  ZECUSDT
4   2020-02-10  71.43  71.65  68.00  69.90   76113.401  ZECUSDT
..         ...    ...    ...    ...    ...         ...      ...
721 2022-01-27  89.74  90.58  82.42  88.51  780623.390  ZECUSDT
722 2022-01-28  88.60  91.77  86.08  91.12  571430.215  ZECUSDT
723 2022-01-29  91.12  97.09  90.54  96.27  558778.710  ZECUSDT
724 2022-01-30  96.27  97.93  91.33  92.93  417823.886  ZECUSDT
725 2022-01-31  92.93  94.78  88.05  94.38  448940.677  ZECUSDT

[726 rows x 7 columns]
processing XEMUSDT.csv (43/145)

h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=481980),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=481980),path=testdata/source/1440d/0000/XEMUSDT.csv
sub_df(0)=
                       open    high     low   close      volume   symbol
date
2021-03-03 07:00:00  0.8085  0.8439  0.7278  0.7453  33743288.0  XEMUSDT
2021-03-03 07:01:00  0.8051  0.8439  0.7278  0.7427  33650974.0  XEMUSDT
2021-03-03 07:02:00  0.7985  0.8439  0.7278  0.7426  33551061.0  XEMUSDT
2021-03-03 07:03:00  0.7996  0.8439  0.7278  0.7400  33504544.0  XEMUSDT
2021-03-03 07:04:00  0.7996  0.8439  0.7278  0.7412  33498821.0  XEMUSDT
...                     ...     ...     ...     ...         ...      ...
2022-01-31 23:55:00  0.1023     NaN     NaN     NaN         NaN  XEMUSDT
2022-01-31 23:56:00  0.1024     NaN     NaN     NaN         NaN  XEMUSDT
2022-01-31 23:57:00  0.1024     NaN     NaN     NaN         NaN  XEMUSDT
2022-01-31 23:58:00  0.1024     NaN     NaN     NaN         NaN  XEMUSDT
2022-01-31 23:59:00  0.1023     NaN     NaN     NaN         NaN  XEMUSDT

[481980 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close       volume   symbol
0   2021-03-04  0.7918  0.8049  0.6666  0.7051   36344364.0  XEMUSDT
1   2021-03-05  0.7062  0.7401  0.6389  0.7157   46489036.0  XEMUSDT
2   2021-03-06  0.7165  0.7988  0.6998  0.7324   71960254.0  XEMUSDT
3   2021-03-07  0.7326  0.7586  0.7043  0.7156   35488470.0  XEMUSDT
4   2021-03-08  0.7157  0.7300  0.6730  0.7174   57070082.0  XEMUSDT
..         ...     ...     ...     ...     ...          ...      ...
329 2022-01-27  0.0973  0.1006  0.0922  0.0982  320751197.0  XEMUSDT
330 2022-01-28  0.0982  0.1000  0.0943  0.0997  307001932.0  XEMUSDT
331 2022-01-29  0.0997  0.1053  0.0993  0.1047  217176482.0  XEMUSDT
332 2022-01-30  0.1047  0.1052  0.1003  0.1025  161635928.0  XEMUSDT
333 2022-01-31  0.1025  0.1032  0.0972  0.1022  207615828.0  XEMUSDT

[334 rows x 7 columns]
processing GTCUSDT.csv (44/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=338190),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=338190),path=testdata/source/1440d/0000/GTCUSDT.csv
sub_df(0)=
                       open  high     low   close     volume   symbol
date
2021-06-11 03:30:00  15.279  18.0  10.559  11.352  5542994.6  GTCUSDT
2021-06-11 03:31:00  14.766  18.0  10.559  11.262  5545323.9  GTCUSDT
2021-06-11 03:32:00  14.521  18.0  10.559  11.251  5546224.6  GTCUSDT
2021-06-11 03:33:00  14.277  18.0  10.559  11.168  5547086.8  GTCUSDT
2021-06-11 03:34:00  13.806  18.0  10.559  11.091  5543186.4  GTCUSDT
...                     ...   ...     ...     ...        ...      ...
2022-01-31 23:55:00   7.324   NaN     NaN     NaN        NaN  GTCUSDT
2022-01-31 23:56:00   7.327   NaN     NaN     NaN        NaN  GTCUSDT
2022-01-31 23:57:00   7.342   NaN     NaN     NaN        NaN  GTCUSDT
2022-01-31 23:58:00   7.323   NaN     NaN     NaN        NaN  GTCUSDT
2022-01-31 23:59:00   7.335   NaN     NaN     NaN        NaN  GTCUSDT

[338190 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close     volume   symbol
0   2021-06-12  11.960  12.200  10.559  11.219  3729245.6  GTCUSDT
1   2021-06-13  11.206  11.268   9.525  10.459  4542564.3  GTCUSDT
2   2021-06-14  10.461  12.083   9.971  10.395  3024666.3  GTCUSDT
3   2021-06-15  10.399  11.099  10.172  10.698  2212576.1  GTCUSDT
4   2021-06-16  10.708  11.190   8.942   9.188  2544230.6  GTCUSDT
..         ...     ...     ...     ...     ...        ...      ...
229 2022-01-27   7.030   7.104   6.422   6.740  5566433.1  GTCUSDT
230 2022-01-28   6.736   7.242   6.587   7.101  5763075.7  GTCUSDT
231 2022-01-29   7.101   7.694   7.065   7.337  5001549.3  GTCUSDT
232 2022-01-30   7.337   7.802   7.077   7.274  6994351.2  GTCUSDT
233 2022-01-31   7.271   7.400   6.787   7.322  4716214.4  GTCUSDT

[234 rows x 7 columns]
processing BCHUSDT.csv (45/145)
h=Int64Index([ 8,  8,  8,  9,  9,  9,  9,  9,  9,  9,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=1115463),m=Int64Index([57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=1115463),path=testdata/source/1440d/0000/BCHUSDT.csv
sub_df(0)=
                       open   high    low   close      volume   symbol
date
2019-12-19 08:57:00  185.00  189.5  182.9  187.34  193994.495  BCHUSDT
2019-12-19 08:58:00  184.75  189.5  182.9  187.28  194175.626  BCHUSDT
2019-12-19 08:59:00  184.75  189.5  182.9  187.27  194299.013  BCHUSDT
2019-12-19 09:00:00  184.75  189.5  182.9  187.43  194508.337  BCHUSDT
2019-12-19 09:01:00  184.75  189.5  182.9  187.51  194667.582  BCHUSDT
...                     ...    ...    ...     ...         ...      ...
2022-01-31 23:55:00  285.34    NaN    NaN     NaN         NaN  BCHUSDT
2022-01-31 23:56:00  285.41    NaN    NaN     NaN         NaN  BCHUSDT
2022-01-31 23:57:00  285.38    NaN    NaN     NaN         NaN  BCHUSDT
2022-01-31 23:58:00  285.14    NaN    NaN     NaN         NaN  BCHUSDT
2022-01-31 23:59:00  284.98    NaN    NaN     NaN         NaN  BCHUSDT

[1115463 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume   symbol
0   2019-12-20  185.99  190.50  183.02  187.41  225130.546  BCHUSDT
1   2019-12-21  187.43  188.49  185.02  186.21  167471.832  BCHUSDT
2   2019-12-22  186.21  197.81  185.70  196.19  116332.603  BCHUSDT
3   2019-12-23  196.19  198.66  187.77  189.61   88983.918  BCHUSDT
4   2019-12-24  189.61  192.11  184.30  188.34   95153.136  BCHUSDT
..         ...     ...     ...     ...     ...         ...      ...
769 2022-01-27  289.03  294.85  277.12  289.40  313519.729  BCHUSDT
770 2022-01-28  289.40  297.21  281.61  296.36  291026.717  BCHUSDT
771 2022-01-29  296.38  301.90  290.98  298.61  183067.844  BCHUSDT
772 2022-01-30  298.66  302.10  287.45  289.71  238641.112  BCHUSDT
773 2022-01-31  289.64  290.29  277.81  284.67  342817.958  BCHUSDT

[774 rows x 7 columns]
processing YFIIUSDT.csv (46/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=742619),m=Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=742619),path=testdata/source/1440d/0000/YFIIUSDT.csv
sub_df(0)=
                       open    high     low   close     volume    symbol
date
2020-09-03 07:01:00  7160.0  7160.0  4502.7  4797.1  11699.284  YFIIUSDT
2020-09-03 07:02:00  5785.6  7100.0  4502.7  4790.4  11700.754  YFIIUSDT
2020-09-03 07:03:00  6681.9  7026.0  4502.7  4762.0  11693.339  YFIIUSDT
2020-09-03 07:04:00  6574.7  7026.0  4502.7  4701.8  11694.024  YFIIUSDT
2020-09-03 07:05:00  6565.7  7026.0  4502.7  4747.2  11693.811  YFIIUSDT
...                     ...     ...     ...     ...        ...       ...
2022-01-31 23:55:00  2350.4     NaN     NaN     NaN        NaN  YFIIUSDT
2022-01-31 23:56:00  2349.9     NaN     NaN     NaN        NaN  YFIIUSDT
2022-01-31 23:57:00  2350.9     NaN     NaN     NaN        NaN  YFIIUSDT
2022-01-31 23:58:00  2350.7     NaN     NaN     NaN        NaN  YFIIUSDT
2022-01-31 23:59:00  2348.3     NaN     NaN     NaN        NaN  YFIIUSDT

[742619 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close     volume    symbol
0   2020-09-04  4899.0  5395.5  3871.2  4297.9  11401.976  YFIIUSDT
1   2020-09-05  4294.7  5582.9  3267.5  3770.0  19961.928  YFIIUSDT
2   2020-09-06  3766.0  4233.1  2755.0  3873.4  16701.743  YFIIUSDT
3   2020-09-07  3865.6  4045.0  3119.5  3706.9   9500.471  YFIIUSDT
4   2020-09-08  3708.9  3766.0  3105.2  3217.6   6317.600  YFIIUSDT
..         ...     ...     ...     ...     ...        ...       ...
510 2022-01-27  2212.9  2303.9  2101.0  2201.7  11565.987  YFIIUSDT
511 2022-01-28  2201.7  2345.7  2151.4  2341.3  10249.656  YFIIUSDT
512 2022-01-29  2341.4  2427.3  2326.9  2375.0   7140.396  YFIIUSDT
513 2022-01-30  2375.7  2394.5  2154.7  2181.9   8790.390  YFIIUSDT
514 2022-01-31  2181.4  2375.5  2076.5  2354.1   8287.859  YFIIUSDT

[515 rows x 7 columns]
processing IOTXUSDT.csv (47/145)

h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=248910),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=248910),path=testdata/source/1440d/0000/IOTXUSDT.csv
sub_df(0)=
                        open     high      low    close        volume  \
date
2021-08-12 03:30:00  0.13700  0.14403  0.10159  0.10436  3.120422e+09
2021-08-12 03:31:00  0.13839  0.14403  0.10159  0.10395  3.120704e+09
2021-08-12 03:32:00  0.13856  0.14403  0.10159  0.10514  3.122755e+09
2021-08-12 03:33:00  0.14081  0.14221  0.10159  0.10521  3.122046e+09
2021-08-12 03:34:00  0.13885  0.14221  0.10159  0.10479  3.121760e+09
...                      ...      ...      ...      ...           ...
2022-01-31 23:55:00  0.07359      NaN      NaN      NaN           NaN
2022-01-31 23:56:00  0.07362      NaN      NaN      NaN           NaN
2022-01-31 23:57:00  0.07374      NaN      NaN      NaN           NaN
2022-01-31 23:58:00  0.07368      NaN      NaN      NaN           NaN
2022-01-31 23:59:00  0.07368      NaN      NaN      NaN           NaN

                       symbol
date
2021-08-12 03:30:00  IOTXUSDT
2021-08-12 03:31:00  IOTXUSDT
2021-08-12 03:32:00  IOTXUSDT
2021-08-12 03:33:00  IOTXUSDT
2021-08-12 03:34:00  IOTXUSDT
...                       ...
2022-01-31 23:55:00  IOTXUSDT
2022-01-31 23:56:00  IOTXUSDT
2022-01-31 23:57:00  IOTXUSDT
2022-01-31 23:58:00  IOTXUSDT
2022-01-31 23:59:00  IOTXUSDT

[248910 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close        volume    symbol
0   2021-08-13  0.11132  0.11553  0.09710  0.09935  2.359731e+09  IOTXUSDT
1   2021-08-14  0.09935  0.10440  0.08905  0.09194  1.646924e+09  IOTXUSDT
2   2021-08-15  0.09194  0.09319  0.08130  0.08614  1.602589e+09  IOTXUSDT
3   2021-08-16  0.08614  0.10292  0.08389  0.08707  2.633338e+09  IOTXUSDT
4   2021-08-17  0.08697  0.08914  0.07405  0.07622  1.669765e+09  IOTXUSDT
..         ...      ...      ...      ...      ...           ...       ...
167 2022-01-27  0.07370  0.07716  0.06963  0.07419  3.601334e+08  IOTXUSDT
168 2022-01-28  0.07417  0.07686  0.07199  0.07646  2.550443e+08  IOTXUSDT
169 2022-01-29  0.07645  0.07927  0.07522  0.07918  2.233689e+08  IOTXUSDT
170 2022-01-30  0.07919  0.08089  0.07399  0.07525  2.630958e+08  IOTXUSDT
171 2022-01-31  0.07523  0.07557  0.07002  0.07366  4.441194e+08  IOTXUSDT

[172 rows x 7 columns]
processing VETUSDT.csv (48/145)
h=Int64Index([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=1033438),m=Int64Index([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=1033438),path=testdata/source/1440d/0000/VETUSDT.csv
sub_df(0)=
                         open     high       low     close       volume  \
date
2020-02-14 08:02:00  0.007720  0.00847  0.007683  0.008284  853612467.0
2020-02-14 08:03:00  0.007731  0.00847  0.007683  0.008301  856815487.0
2020-02-14 08:04:00  0.007689  0.00847  0.007683  0.008305  856867729.0
2020-02-14 08:05:00  0.007729  0.00847  0.007683  0.008305  856285556.0
2020-02-14 08:06:00  0.007724  0.00847  0.007701  0.008312  856212046.0
...                       ...      ...       ...       ...          ...
2022-01-31 23:55:00  0.053640      NaN       NaN       NaN          NaN
2022-01-31 23:56:00  0.053690      NaN       NaN       NaN          NaN
2022-01-31 23:57:00  0.053720      NaN       NaN       NaN          NaN
2022-01-31 23:58:00  0.053770      NaN       NaN       NaN          NaN
2022-01-31 23:59:00  0.053760      NaN       NaN       NaN          NaN

                      symbol
date
2020-02-14 08:02:00  VETUSDT
2020-02-14 08:03:00  VETUSDT
2020-02-14 08:04:00  VETUSDT
2020-02-14 08:05:00  VETUSDT
2020-02-14 08:06:00  VETUSDT
...                      ...
2022-01-31 23:55:00  VETUSDT
2022-01-31 23:56:00  VETUSDT
2022-01-31 23:57:00  VETUSDT
2022-01-31 23:58:00  VETUSDT
2022-01-31 23:59:00  VETUSDT

[1033438 rows x 6 columns]
sub_df(1)=
          date      open      high       low     close        volume   symbol
0   2020-02-15  0.008308  0.008460  0.007233  0.007479  9.978609e+08  VETUSDT
1   2020-02-16  0.007478  0.007681  0.006410  0.007102  8.533560e+08  VETUSDT
2   2020-02-17  0.007096  0.007144  0.006255  0.006750  6.286308e+08  VETUSDT
3   2020-02-18  0.006753  0.007262  0.006621  0.007060  8.795978e+08  VETUSDT
4   2020-02-19  0.007063  0.007300  0.006120  0.006481  6.025947e+08  VETUSDT
..         ...       ...       ...       ...       ...           ...      ...
712 2022-01-27  0.053340  0.054590  0.049980  0.052290  2.260402e+09  VETUSDT
713 2022-01-28  0.052300  0.054120  0.050650  0.053840  1.689456e+09  VETUSDT
714 2022-01-29  0.053840  0.055490  0.053230  0.054480  1.338774e+09  VETUSDT
715 2022-01-30  0.054480  0.055590  0.051360  0.052500  1.303604e+09  VETUSDT
716 2022-01-31  0.052510  0.053920  0.050270  0.053800  1.458105e+09  VETUSDT

[717 rows x 7 columns]
processing QTUMUSDT.csv (49/145)
h=Int64Index([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=1024794),m=Int64Index([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=1024794),path=testdata/source/1440d/0000/QTUMUSDT.csv
sub_df(0)=
                      open   high  low  close    volume    symbol
date
2020-02-20 08:06:00  2.435  2.466  2.3  2.425  442291.1  QTUMUSDT
2020-02-20 08:07:00  2.448  2.466  2.3  2.422  442227.6  QTUMUSDT
2020-02-20 08:08:00  2.451  2.466  2.3  2.423  440500.7  QTUMUSDT
2020-02-20 08:09:00  2.450  2.466  2.3  2.423  440414.0  QTUMUSDT
2020-02-20 08:10:00  2.446  2.466  2.3  2.424  439857.6  QTUMUSDT
...                    ...    ...  ...    ...       ...       ...
2022-01-31 23:55:00  6.066    NaN  NaN    NaN       NaN  QTUMUSDT
2022-01-31 23:56:00  6.067    NaN  NaN    NaN       NaN  QTUMUSDT
2022-01-31 23:57:00  6.072    NaN  NaN    NaN       NaN  QTUMUSDT
2022-01-31 23:58:00  6.072    NaN  NaN    NaN       NaN  QTUMUSDT
2022-01-31 23:59:00  6.070    NaN  NaN    NaN       NaN  QTUMUSDT

[1024794 rows x 6 columns]
sub_df(1)=
          date   open   high    low  close     volume    symbol
0   2020-02-21  2.391  2.475  2.359  2.416   345033.4  QTUMUSDT
1   2020-02-22  2.419  2.437  2.344  2.391   315412.3  QTUMUSDT
2   2020-02-23  2.393  2.508  2.391  2.500   375696.4  QTUMUSDT
3   2020-02-24  2.491  2.504  2.278  2.360   501921.1  QTUMUSDT
4   2020-02-25  2.361  2.621  2.316  2.383  2226704.5  QTUMUSDT
..         ...    ...    ...    ...    ...        ...       ...
706 2022-01-27  5.582  5.738  5.363  5.623  4379647.9  QTUMUSDT
707 2022-01-28  5.622  5.839  5.513  5.815  4081810.0  QTUMUSDT
708 2022-01-29  5.813  6.078  5.798  5.965  2560833.4  QTUMUSDT
709 2022-01-30  5.964  6.174  5.823  5.962  2642123.4  QTUMUSDT
710 2022-01-31  5.958  6.081  5.659  6.061  3186684.7  QTUMUSDT

[711 rows x 7 columns]
processing ARUSDT.csv (50/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=181230),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=181230),path=testdata/source/1440d/0000/ARUSDT.csv
sub_df(0)=
                       open    high   low   close    volume  symbol
date
2021-09-28 03:30:00  41.780  41.780  38.0  41.086  187741.9  ARUSDT
2021-09-28 03:31:00  41.365  41.674  38.0  41.102  187077.0  ARUSDT
2021-09-28 03:32:00  41.100  41.674  38.0  41.177  185534.2  ARUSDT
2021-09-28 03:33:00  41.024  41.674  38.0  41.343  185398.0  ARUSDT
2021-09-28 03:34:00  41.024  41.674  38.0  41.355  185334.6  ARUSDT
...                     ...     ...   ...     ...       ...     ...
2022-01-31 23:55:00  38.969     NaN   NaN     NaN       NaN  ARUSDT
2022-01-31 23:56:00  39.023     NaN   NaN     NaN       NaN  ARUSDT
2022-01-31 23:57:00  39.069     NaN   NaN     NaN       NaN  ARUSDT
2022-01-31 23:58:00  39.043     NaN   NaN     NaN       NaN  ARUSDT
2022-01-31 23:59:00  38.973     NaN   NaN     NaN       NaN  ARUSDT

[181230 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close     volume  symbol
0   2021-09-29  38.311  45.131  38.000  40.633   731537.4  ARUSDT
1   2021-09-30  40.640  43.734  40.180  43.364   337757.1  ARUSDT
2   2021-10-01  43.356  49.576  42.566  48.867   677330.2  ARUSDT
3   2021-10-02  48.860  58.584  46.546  58.462   689907.4  ARUSDT
4   2021-10-03  58.342  59.187  54.020  57.538   997950.6  ARUSDT
..         ...     ...     ...     ...     ...        ...     ...
120 2022-01-27  30.193  31.580  28.573  30.303  1466854.8  ARUSDT
121 2022-01-28  30.299  32.079  29.100  31.728  1331265.4  ARUSDT
122 2022-01-29  31.729  35.924  31.464  34.964  1792013.5  ARUSDT
123 2022-01-30  34.968  37.700  33.701  35.867  3631984.2  ARUSDT
124 2022-01-31  35.862  41.300  34.095  38.879  3635932.0  ARUSDT

[125 rows x 7 columns]
processing BNBUSDT.csv (51/145)

h=Int64Index([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=1039199),m=Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=1039199),path=testdata/source/1440d/0000/BNBUSDT.csv
sub_df(0)=
                        open    high     low   close      volume   symbol
date
2020-02-10 08:01:00   25.070  25.907  24.031  24.532  1987766.51  BNBUSDT
2020-02-10 08:02:00   25.000  25.907  24.031  24.500  1988769.37  BNBUSDT
2020-02-10 08:03:00   25.102  25.907  24.031  24.497  1988522.33  BNBUSDT
2020-02-10 08:04:00   25.172  25.907  24.031  24.541  1988308.57  BNBUSDT
2020-02-10 08:05:00   25.230  25.907  24.031  24.552  1981455.15  BNBUSDT
...                      ...     ...     ...     ...         ...      ...
2022-01-31 23:55:00  376.070     NaN     NaN     NaN         NaN  BNBUSDT
2022-01-31 23:56:00  375.180     NaN     NaN     NaN         NaN  BNBUSDT
2022-01-31 23:57:00  375.350     NaN     NaN     NaN         NaN  BNBUSDT
2022-01-31 23:58:00  374.830     NaN     NaN     NaN         NaN  BNBUSDT
2022-01-31 23:59:00  374.480     NaN     NaN     NaN         NaN  BNBUSDT

[1039199 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close      volume   symbol
0   2020-02-11   25.190   25.864   24.250   25.705  1783061.99  BNBUSDT
1   2020-02-12   25.705   26.980   25.347   26.451  1311285.47  BNBUSDT
2   2020-02-13   26.452   27.397   24.580   25.456  1451755.42  BNBUSDT
3   2020-02-14   25.455   26.697   25.043   26.384  1271237.03  BNBUSDT
4   2020-02-15   26.373   26.600   23.250   24.239  1601280.92  BNBUSDT
..         ...      ...      ...      ...      ...         ...      ...
716 2022-01-27  374.780  392.880  359.280  389.360  1635176.05  BNBUSDT
717 2022-01-28  389.370  396.390  375.260  385.840  1690112.66  BNBUSDT
718 2022-01-29  385.830  397.340  380.530  389.040  1114435.13  BNBUSDT
719 2022-01-30  389.040  389.270  372.130  376.840   981385.00  BNBUSDT
720 2022-01-31  376.840  385.100  364.770  374.380  1151928.43  BNBUSDT

[721 rows x 7 columns]
processing YFIUSDT.csv (52/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=746940),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=746940),path=testdata/source/1440d/0000/YFIUSDT.csv
sub_df(0)=
                        open     high      low    close    volume   symbol
date
2020-08-31 07:00:00  32000.0  39681.9  31126.3  33674.0  7198.512  YFIUSDT
2020-08-31 07:01:00  32400.0  39681.9  31126.3  33622.9  7198.125  YFIUSDT
2020-08-31 07:02:00  32200.5  39681.9  31126.3  33349.9  7195.750  YFIUSDT
2020-08-31 07:03:00  32210.0  39681.9  31126.3  33758.0  7191.200  YFIUSDT
2020-08-31 07:04:00  31940.0  39681.9  31126.3  33775.4  7183.958  YFIUSDT
...                      ...      ...      ...      ...       ...      ...
2022-01-31 23:55:00  24804.0      NaN      NaN      NaN       NaN  YFIUSDT
2022-01-31 23:56:00  24810.0      NaN      NaN      NaN       NaN  YFIUSDT
2022-01-31 23:57:00  24824.0      NaN      NaN      NaN       NaN  YFIUSDT
2022-01-31 23:58:00  24824.0      NaN      NaN      NaN       NaN  YFIUSDT
2022-01-31 23:59:00  24815.0      NaN      NaN      NaN       NaN  YFIUSDT

[746940 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close    volume   symbol
0   2020-09-01  34845.4  37000.0  31500.0  32006.3  4308.466  YFIUSDT
1   2020-09-02  32000.0  32852.2  25450.0  31934.5  4936.519  YFIUSDT
2   2020-09-03  31934.4  33406.4  27575.0  29408.3  3622.188  YFIUSDT
3   2020-09-04  29341.8  31564.7  23056.3  27286.5  2579.716  YFIUSDT
4   2020-09-05  27275.3  28683.9  18029.9  22184.6  4451.227  YFIUSDT
..         ...      ...      ...      ...      ...       ...      ...
513 2022-01-27  24175.0  24833.0  23051.0  23880.0  2157.709  YFIUSDT
514 2022-01-28  23879.0  24167.0  22343.0  23468.0  2011.881  YFIUSDT
515 2022-01-29  23469.0  24691.0  23389.0  24268.0  1700.734  YFIUSDT
516 2022-01-30  24267.0  25553.0  23400.0  23794.0  1764.360  YFIUSDT
517 2022-01-31  23794.0  24843.0  22834.0  24817.0  1647.602  YFIUSDT

[518 rows x 7 columns]
processing BAKEUSDT.csv (53/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=371100),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=371100),path=testdata/source/1440d/0000/BAKEUSDT.csv
sub_df(0)=
                       open    high     low   close      volume    symbol
date
2021-05-19 07:00:00  5.4541  5.9073  3.1064  4.7182  13263969.0  BAKEUSDT
2021-05-19 07:01:00  5.5048  5.9073  3.1064  4.7700  13251878.0  BAKEUSDT
2021-05-19 07:02:00  5.5332  5.9073  3.1064  4.7694  13245388.0  BAKEUSDT
2021-05-19 07:03:00  5.5601  5.9073  3.1064  4.7758  13240770.0  BAKEUSDT
2021-05-19 07:04:00  5.6073  5.9073  3.1064  4.8033  13234779.0  BAKEUSDT
...                     ...     ...     ...     ...         ...       ...
2022-01-31 23:55:00  0.6199     NaN     NaN     NaN         NaN  BAKEUSDT
2022-01-31 23:56:00  0.6199     NaN     NaN     NaN         NaN  BAKEUSDT
2022-01-31 23:57:00  0.6205     NaN     NaN     NaN         NaN  BAKEUSDT
2022-01-31 23:58:00  0.6205     NaN     NaN     NaN         NaN  BAKEUSDT
2022-01-31 23:59:00  0.6197     NaN     NaN     NaN         NaN  BAKEUSDT

[371100 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume    symbol
0   2021-05-20  4.0256  5.4331  3.3302  4.9231  10820348.0  BAKEUSDT
1   2021-05-21  4.9246  5.2427  2.9706  3.6863  14498988.0  BAKEUSDT
2   2021-05-22  3.6919  3.8362  3.0087  3.0830  12342151.0  BAKEUSDT
3   2021-05-23  3.0828  3.2156  1.8651  2.3555  35468341.0  BAKEUSDT
4   2021-05-24  2.3551  3.5500  2.3267  3.3334  38495518.0  BAKEUSDT
..         ...     ...     ...     ...     ...         ...       ...
252 2022-01-27  0.6132  0.6259  0.5801  0.6081  61899479.0  BAKEUSDT
253 2022-01-28  0.6081  0.6190  0.5870  0.6106  48917044.0  BAKEUSDT
254 2022-01-29  0.6106  0.6352  0.6078  0.6268  35066721.0  BAKEUSDT
255 2022-01-30  0.6270  0.6400  0.6058  0.6188  39452277.0  BAKEUSDT
256 2022-01-31  0.6188  0.6221  0.5872  0.6188  47614068.0  BAKEUSDT

[257 rows x 7 columns]
processing LTCUSDT.csv (54/145)
h=Int64Index([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=1085271),m=Int64Index([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=1085271),path=testdata/source/1440d/0000/LTCUSDT.csv
sub_df(0)=
                       open   high    low  close      volume   symbol
date
2020-01-09 08:09:00   45.32  45.77  43.87  44.22  297003.651  LTCUSDT
2020-01-09 08:10:00   45.34  45.77  43.87  44.23  297331.883  LTCUSDT
2020-01-09 08:11:00   45.75  45.77  43.87  44.24  297338.622  LTCUSDT
2020-01-09 08:12:00   45.74  45.77  43.87  44.22  297589.149  LTCUSDT
2020-01-09 08:13:00   45.71  45.71  43.87  44.23  297856.990  LTCUSDT
...                     ...    ...    ...    ...         ...      ...
2022-01-31 23:55:00  109.39    NaN    NaN    NaN         NaN  LTCUSDT
2022-01-31 23:56:00  109.44    NaN    NaN    NaN         NaN  LTCUSDT
2022-01-31 23:57:00  109.53    NaN    NaN    NaN         NaN  LTCUSDT
2022-01-31 23:58:00  109.46    NaN    NaN    NaN         NaN  LTCUSDT
2022-01-31 23:59:00  109.51    NaN    NaN    NaN         NaN  LTCUSDT

[1085271 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close       volume   symbol
0   2020-01-10   44.73   49.63   43.80   49.04   384284.072  LTCUSDT
1   2020-01-11   49.03   51.99   47.76   49.25   545784.433  LTCUSDT
2   2020-01-12   49.30   51.75   48.78   51.33   528807.006  LTCUSDT
3   2020-01-13   51.33   51.42   48.90   49.58   481361.430  LTCUSDT
4   2020-01-14   49.60   61.21   49.58   58.55  1387911.639  LTCUSDT
..         ...     ...     ...     ...     ...          ...      ...
748 2022-01-27  106.92  109.93  102.80  106.84  2020455.603  LTCUSDT
749 2022-01-28  106.84  110.00  105.15  109.34  1613466.928  LTCUSDT
750 2022-01-29  109.36  112.33  107.42  110.75  1195197.172  LTCUSDT
751 2022-01-30  110.75  112.19  106.89  108.40  1254061.471  LTCUSDT
752 2022-01-31  108.40  111.24  104.13  109.42  1871703.487  LTCUSDT

[753 rows x 7 columns]
processing EGLDUSDT.csv (55/145)

h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=726780),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=726780),path=testdata/source/1440d/0000/EGLDUSDT.csv
sub_df(0)=
                        open    high   low   close    volume    symbol
date
2020-09-14 07:00:00   13.294  15.213  12.7  14.772  524827.0  EGLDUSDT
2020-09-14 07:01:00   13.010  15.213  12.7  14.772  524614.3  EGLDUSDT
2020-09-14 07:02:00   13.160  15.213  12.7  14.843  526902.6  EGLDUSDT
2020-09-14 07:03:00   13.164  15.213  12.7  14.826  528518.2  EGLDUSDT
2020-09-14 07:04:00   13.164  15.213  12.7  14.825  529177.8  EGLDUSDT
...                      ...     ...   ...     ...       ...       ...
2022-01-31 23:55:00  145.940     NaN   NaN     NaN       NaN  EGLDUSDT
2022-01-31 23:56:00  146.040     NaN   NaN     NaN       NaN  EGLDUSDT
2022-01-31 23:57:00  146.060     NaN   NaN     NaN       NaN  EGLDUSDT
2022-01-31 23:58:00  145.960     NaN   NaN     NaN       NaN  EGLDUSDT
2022-01-31 23:59:00  145.610     NaN   NaN     NaN       NaN  EGLDUSDT

[726780 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close    volume    symbol
0   2020-09-15   13.997   15.039   12.837   13.066  590234.6  EGLDUSDT
1   2020-09-16   13.040   13.047   11.830   12.584  295253.6  EGLDUSDT
2   2020-09-17   12.578   12.880   11.740   12.044  233613.2  EGLDUSDT
3   2020-09-18   12.061   12.308   10.874   11.233  224249.0  EGLDUSDT
4   2020-09-19   11.231   12.241   11.182   11.950  254928.5  EGLDUSDT
..         ...      ...      ...      ...      ...       ...       ...
499 2022-01-27  140.020  146.840  132.350  141.740  658129.6  EGLDUSDT
500 2022-01-28  141.700  146.560  136.050  143.770  455969.6  EGLDUSDT
501 2022-01-29  143.770  151.700  142.850  149.380  403069.4  EGLDUSDT
502 2022-01-30  149.390  151.640  139.600  140.950  415292.5  EGLDUSDT
503 2022-01-31  140.930  147.840  133.860  145.370  413299.3  EGLDUSDT

[504 rows x 7 columns]
processing CELRUSDT.csv (56/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=444540),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=444540),path=testdata/source/1440d/0000/CELRUSDT.csv
sub_df(0)=
                        open     high    low    close       volume    symbol
date
2021-03-29 07:00:00  0.09390  0.09700  0.085  0.08926  225015058.0  CELRUSDT
2021-03-29 07:01:00  0.09313  0.09628  0.085  0.08882  225095469.0  CELRUSDT
2021-03-29 07:02:00  0.09301  0.09628  0.085  0.08840  226160025.0  CELRUSDT
2021-03-29 07:03:00  0.09354  0.09628  0.085  0.08841  226320632.0  CELRUSDT
2021-03-29 07:04:00  0.09356  0.09628  0.085  0.08832  226108649.0  CELRUSDT
...                      ...      ...    ...      ...          ...       ...
2022-01-31 23:55:00  0.04977      NaN    NaN      NaN          NaN  CELRUSDT
2022-01-31 23:56:00  0.04978      NaN    NaN      NaN          NaN  CELRUSDT
2022-01-31 23:57:00  0.04983      NaN    NaN      NaN          NaN  CELRUSDT
2022-01-31 23:58:00  0.04985      NaN    NaN      NaN          NaN  CELRUSDT
2022-01-31 23:59:00  0.04986      NaN    NaN      NaN          NaN  CELRUSDT

[444540 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close        volume    symbol
0   2021-03-30  0.08727  0.09542  0.08660  0.09241  3.133941e+08  CELRUSDT
1   2021-03-31  0.09248  0.09277  0.07691  0.08393  3.232238e+08  CELRUSDT
2   2021-04-01  0.08384  0.08812  0.07852  0.07959  2.910063e+08  CELRUSDT
3   2021-04-02  0.07964  0.08583  0.07623  0.08038  2.408574e+08  CELRUSDT
4   2021-04-03  0.08038  0.08756  0.07533  0.07546  3.678008e+08  CELRUSDT
..         ...      ...      ...      ...      ...           ...       ...
303 2022-01-27  0.05060  0.05194  0.04715  0.04912  1.685843e+09  CELRUSDT
304 2022-01-28  0.04911  0.05113  0.04658  0.05060  1.161348e+09  CELRUSDT
305 2022-01-29  0.05061  0.05200  0.04957  0.05113  1.043319e+09  CELRUSDT
306 2022-01-30  0.05112  0.05359  0.04879  0.04948  1.225646e+09  CELRUSDT
307 2022-01-31  0.04946  0.05061  0.04701  0.04983  1.107152e+09  CELRUSDT

[308 rows x 7 columns]
processing CTSIUSDT.csv (57/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=140910),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=140910),path=testdata/source/1440d/0000/CTSIUSDT.csv
sub_df(0)=
                       open    high     low   close      volume    symbol
date
2021-10-26 03:30:00  0.8369  0.8905  0.7974  0.8106  37462398.0  CTSIUSDT
2021-10-26 03:31:00  0.8287  0.8905  0.7974  0.8109  37127023.0  CTSIUSDT
2021-10-26 03:32:00  0.8410  0.8905  0.7974  0.8110  36655852.0  CTSIUSDT
2021-10-26 03:33:00  0.8429  0.8905  0.7974  0.8113  36298727.0  CTSIUSDT
2021-10-26 03:34:00  0.8440  0.8905  0.7974  0.8113  36174287.0  CTSIUSDT
...                     ...     ...     ...     ...         ...       ...
2022-01-31 23:55:00  0.4639     NaN     NaN     NaN         NaN  CTSIUSDT
2022-01-31 23:56:00  0.4637     NaN     NaN     NaN         NaN  CTSIUSDT
2022-01-31 23:57:00  0.4637     NaN     NaN     NaN         NaN  CTSIUSDT
2022-01-31 23:58:00  0.4638     NaN     NaN     NaN         NaN  CTSIUSDT
2022-01-31 23:59:00  0.4639     NaN     NaN     NaN         NaN  CTSIUSDT

[140910 rows x 6 columns]
sub_df(1)=
         date    open    high     low   close      volume    symbol
0  2021-10-27  0.8058  0.8175  0.6800  0.7033  20425910.0  CTSIUSDT
1  2021-10-28  0.7033  0.7459  0.7017  0.7299  10828790.0  CTSIUSDT
2  2021-10-29  0.7300  0.7697  0.7239  0.7464  12265363.0  CTSIUSDT
3  2021-10-30  0.7471  0.8226  0.7219  0.7400  25621721.0  CTSIUSDT
4  2021-10-31  0.7399  0.8000  0.7339  0.7787  23806557.0  CTSIUSDT
..        ...     ...     ...     ...     ...         ...       ...
92 2022-01-27  0.4502  0.4664  0.4258  0.4468  23490075.0  CTSIUSDT
93 2022-01-28  0.4464  0.4726  0.4270  0.4522  23139696.0  CTSIUSDT
94 2022-01-29  0.4523  0.4680  0.4470  0.4638  25978096.0  CTSIUSDT
95 2022-01-30  0.4641  0.4768  0.4428  0.4513  26533617.0  CTSIUSDT
96 2022-01-31  0.4507  0.4684  0.4236  0.4629  23369385.0  CTSIUSDT

[97 rows x 7 columns]
processing STMXUSDT.csv (58/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=454620),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=454620),path=testdata/source/1440d/0000/STMXUSDT.csv
sub_df(0)=
                        open     high      low    close       volume    symbol
date
2021-03-22 07:00:00  0.06162  0.06277  0.04374  0.04468  732916480.0  STMXUSDT
2021-03-22 07:01:00  0.06120  0.06188  0.04374  0.04477  733832216.0  STMXUSDT
2021-03-22 07:02:00  0.06081  0.06188  0.04374  0.04530  734307192.0  STMXUSDT
2021-03-22 07:03:00  0.06068  0.06188  0.04374  0.04530  734786299.0  STMXUSDT
2021-03-22 07:04:00  0.06024  0.06188  0.04374  0.04542  734360339.0  STMXUSDT
...                      ...      ...      ...      ...          ...       ...
2022-01-31 23:55:00  0.01539      NaN      NaN      NaN          NaN  STMXUSDT
2022-01-31 23:56:00  0.01538      NaN      NaN      NaN          NaN  STMXUSDT
2022-01-31 23:57:00  0.01538      NaN      NaN      NaN          NaN  STMXUSDT
2022-01-31 23:58:00  0.01538      NaN      NaN      NaN          NaN  STMXUSDT
2022-01-31 23:59:00  0.01538      NaN      NaN      NaN          NaN  STMXUSDT

[454620 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close        volume    symbol
0   2021-03-23  0.05246  0.06300  0.04374  0.05080  1.250385e+09  STMXUSDT
1   2021-03-24  0.05087  0.06600  0.04977  0.05389  1.771918e+09  STMXUSDT
2   2021-03-25  0.05389  0.05712  0.04837  0.05072  5.631995e+08  STMXUSDT
3   2021-03-26  0.05065  0.05615  0.04990  0.05602  4.204862e+08  STMXUSDT
4   2021-03-27  0.05602  0.06094  0.05403  0.05894  5.290942e+08  STMXUSDT
..         ...      ...      ...      ...      ...           ...       ...
310 2022-01-27  0.01342  0.01430  0.01295  0.01360  9.363148e+08  STMXUSDT
311 2022-01-28  0.01360  0.01444  0.01346  0.01417  9.543705e+08  STMXUSDT
312 2022-01-29  0.01417  0.01560  0.01412  0.01527  1.171575e+09  STMXUSDT
313 2022-01-30  0.01527  0.01548  0.01461  0.01507  1.269304e+09  STMXUSDT
314 2022-01-31  0.01507  0.01549  0.01399  0.01535  1.373963e+09  STMXUSDT

[315 rows x 7 columns]
processing COMPUSDT.csv (59/145)

h=Int64Index([ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=836100),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=836100),path=testdata/source/1440d/0000/COMPUSDT.csv
sub_df(0)=
                       open    high     low   close     volume    symbol
date
2020-06-30 09:00:00  231.58  232.07  210.84  213.03  73410.169  COMPUSDT
2020-06-30 09:01:00  230.94  230.94  210.84  213.33  73247.943  COMPUSDT
2020-06-30 09:02:00  229.72  229.99  210.84  213.37  72976.944  COMPUSDT
2020-06-30 09:03:00  229.60  229.99  210.84  213.46  72865.823  COMPUSDT
2020-06-30 09:04:00  229.39  229.99  210.84  213.54  72762.448  COMPUSDT
...                     ...     ...     ...     ...        ...       ...
2022-01-31 23:55:00  121.78     NaN     NaN     NaN        NaN  COMPUSDT
2022-01-31 23:56:00  122.00     NaN     NaN     NaN        NaN  COMPUSDT
2022-01-31 23:57:00  122.14     NaN     NaN     NaN        NaN  COMPUSDT
2022-01-31 23:58:00  122.10     NaN     NaN     NaN        NaN  COMPUSDT
2022-01-31 23:59:00  121.99     NaN     NaN     NaN        NaN  COMPUSDT

[836100 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume    symbol
0   2020-07-01  216.38  216.80  200.00  201.05   66459.787  COMPUSDT
1   2020-07-02  201.06  205.00  173.98  179.04  182149.566  COMPUSDT
2   2020-07-03  179.04  191.56  170.05  171.73  135389.969  COMPUSDT
3   2020-07-04  171.74  186.90  163.01  180.39  196237.080  COMPUSDT
4   2020-07-05  180.15  205.00  176.60  201.01  248072.586  COMPUSDT
..         ...     ...     ...     ...     ...         ...       ...
575 2022-01-27  125.41  129.62  118.54  123.24  244625.577  COMPUSDT
576 2022-01-28  123.22  125.96  118.40  122.52  219351.911  COMPUSDT
577 2022-01-29  122.54  126.84  121.45  123.99  213520.278  COMPUSDT
578 2022-01-30  123.98  124.34  116.22  117.63  253646.429  COMPUSDT
579 2022-01-31  117.60  122.97  112.71  121.70  304280.987  COMPUSDT

[580 rows x 7 columns]
processing THETAUSDT.csv (60/145)
h=Int64Index([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=885119),m=Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=885119),path=testdata/source/1440d/0000/THETAUSDT.csv
sub_df(0)=
                       open   high     low   close       volume     symbol
date
2020-05-27 08:01:00  0.4040  0.515  0.2777  0.3174  526235766.4  THETAUSDT
2020-05-27 08:02:00  0.4279  0.515  0.2777  0.3175  526200762.6  THETAUSDT
2020-05-27 08:03:00  0.4284  0.515  0.2777  0.3182  526061164.8  THETAUSDT
2020-05-27 08:04:00  0.4240  0.515  0.2777  0.3171  525975778.1  THETAUSDT
2020-05-27 08:05:00  0.4282  0.515  0.2777  0.3158  525919305.8  THETAUSDT
...                     ...    ...     ...     ...          ...        ...
2022-01-31 23:55:00  2.9430    NaN     NaN     NaN          NaN  THETAUSDT
2022-01-31 23:56:00  2.9410    NaN     NaN     NaN          NaN  THETAUSDT
2022-01-31 23:57:00  2.9430    NaN     NaN     NaN          NaN  THETAUSDT
2022-01-31 23:58:00  2.9390    NaN     NaN     NaN          NaN  THETAUSDT
2022-01-31 23:59:00  2.9350    NaN     NaN     NaN          NaN  THETAUSDT

[885119 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close        volume     symbol
0   2020-05-28  0.3246  0.3555  0.2777  0.3126  1.440938e+08  THETAUSDT
1   2020-05-29  0.3127  0.3350  0.2900  0.3097  6.336364e+07  THETAUSDT
2   2020-05-30  0.3097  0.3112  0.2822  0.2890  4.745198e+07  THETAUSDT
3   2020-05-31  0.2890  0.2910  0.2404  0.2472  5.357418e+07  THETAUSDT
4   2020-06-01  0.2471  0.2910  0.2430  0.2717  6.112984e+07  THETAUSDT
..         ...     ...     ...     ...     ...           ...        ...
609 2022-01-27  2.8070  3.1790  2.7640  2.8900  1.307448e+08  THETAUSDT
610 2022-01-28  2.8900  3.0050  2.7900  2.9400  4.847065e+07  THETAUSDT
611 2022-01-29  2.9400  3.0210  2.8710  2.9840  2.635553e+07  THETAUSDT
612 2022-01-30  2.9850  3.1110  2.7990  2.8760  2.957000e+07  THETAUSDT
613 2022-01-31  2.8750  2.9450  2.7010  2.9330  3.396892e+07  THETAUSDT

[614 rows x 7 columns]
processing DOGEBUSD.csv (61/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=240270),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=240270),path=testdata/source/1440d/0000/DOGEBUSD.csv
sub_df(0)=
                        open     high      low    close      volume    symbol
date
2021-08-18 03:30:00  0.29095  0.32559  0.28407  0.29662  63661901.0  DOGEBUSD
2021-08-18 03:31:00  0.29065  0.32559  0.28407  0.29641  63702089.0  DOGEBUSD
2021-08-18 03:32:00  0.29025  0.32559  0.28407  0.29647  63744464.0  DOGEBUSD
2021-08-18 03:33:00  0.29006  0.32559  0.28407  0.29798  63758376.0  DOGEBUSD
2021-08-18 03:34:00  0.29097  0.32559  0.28407  0.29896  63803191.0  DOGEBUSD
...                      ...      ...      ...      ...         ...       ...
2022-01-31 23:55:00  0.14167      NaN      NaN      NaN         NaN  DOGEBUSD
2022-01-31 23:56:00  0.14174      NaN      NaN      NaN         NaN  DOGEBUSD
2022-01-31 23:57:00  0.14175      NaN      NaN      NaN         NaN  DOGEBUSD
2022-01-31 23:58:00  0.14171      NaN      NaN      NaN         NaN  DOGEBUSD
2022-01-31 23:59:00  0.14167      NaN      NaN      NaN         NaN  DOGEBUSD

[240270 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close       volume    symbol
0   2021-08-19  0.30382  0.31972  0.29391  0.31820   77874448.0  DOGEBUSD
1   2021-08-20  0.31832  0.33415  0.31423  0.32748  120455776.0  DOGEBUSD
2   2021-08-21  0.32750  0.33157  0.31468  0.31724   92439012.0  DOGEBUSD
3   2021-08-22  0.31709  0.32200  0.30538  0.31532   96146304.0  DOGEBUSD
4   2021-08-23  0.31532  0.32998  0.31336  0.31842   86852761.0  DOGEBUSD
..         ...      ...      ...      ...      ...          ...       ...
161 2022-01-27  0.14316  0.14596  0.13615  0.14141  324648249.0  DOGEBUSD
162 2022-01-28  0.14140  0.14262  0.13772  0.14143  267278838.0  DOGEBUSD
163 2022-01-29  0.14142  0.14422  0.14026  0.14292  166306620.0  DOGEBUSD
164 2022-01-30  0.14293  0.14367  0.13804  0.13915  167007692.0  DOGEBUSD
165 2022-01-31  0.13915  0.14247  0.13629  0.14156  325080102.0  DOGEBUSD

[166 rows x 7 columns]
processing ATOMUSDT.csv (62/145)
h=Int64Index([12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=1043269),m=Int64Index([11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=1043269),path=testdata/source/1440d/0000/ATOMUSDT.csv
sub_df(0)=
                       open  high    low  close      volume    symbol
date
2020-02-07 12:11:00   4.574  4.95  4.485  4.787  1718565.98  ATOMUSDT
2020-02-07 12:12:00   4.581  4.95  4.485  4.786  1718625.46  ATOMUSDT
2020-02-07 12:13:00   4.584  4.95  4.485  4.778  1719054.30  ATOMUSDT
2020-02-07 12:14:00   4.590  4.95  4.485  4.788  1719126.01  ATOMUSDT
2020-02-07 12:15:00   4.593  4.95  4.485  4.782  1713977.49  ATOMUSDT
...                     ...   ...    ...    ...         ...       ...
2022-01-31 23:55:00  28.077   NaN    NaN    NaN         NaN  ATOMUSDT
2022-01-31 23:56:00  28.100   NaN    NaN    NaN         NaN  ATOMUSDT
2022-01-31 23:57:00  28.119   NaN    NaN    NaN         NaN  ATOMUSDT
2022-01-31 23:58:00  28.082   NaN    NaN    NaN         NaN  ATOMUSDT
2022-01-31 23:59:00  28.084   NaN    NaN    NaN         NaN  ATOMUSDT

[1043269 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close       volume    symbol
0   2020-02-08   4.817   4.835   4.485   4.647   1234406.02  ATOMUSDT
1   2020-02-09   4.642   4.810   4.626   4.760    985383.90  ATOMUSDT
2   2020-02-10   4.760   4.810   4.547   4.782   1026402.54  ATOMUSDT
3   2020-02-11   4.774   5.237   4.696   5.118   1946745.80  ATOMUSDT
4   2020-02-12   5.119   5.346   5.050   5.117   1592273.17  ATOMUSDT
..         ...     ...     ...     ...     ...          ...       ...
719 2022-01-27  32.324  32.913  28.530  30.045  29101176.73  ATOMUSDT
720 2022-01-28  30.043  30.323  27.690  29.433  26315160.71  ATOMUSDT
721 2022-01-29  29.434  30.235  28.250  29.054  17494816.49  ATOMUSDT
722 2022-01-30  29.054  29.174  26.354  27.148  15569209.43  ATOMUSDT
723 2022-01-31  27.147  28.930  25.500  28.048  20936968.03  ATOMUSDT

[724 rows x 7 columns]
processing ANKRUSDT.csv (63/145)

h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=533820),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=533820),path=testdata/source/1440d/0000/ANKRUSDT.csv
sub_df(0)=
                         open      high       low     close      volume  \
date
2021-01-26 07:00:00  0.010950  0.010950  0.009765  0.010032  96050752.0
2021-01-26 07:01:00  0.010306  0.010784  0.009765  0.010047  95486640.0
2021-01-26 07:02:00  0.010499  0.010760  0.009765  0.010040  89801650.0
2021-01-26 07:03:00  0.010508  0.010760  0.009765  0.010041  89170698.0
2021-01-26 07:04:00  0.010500  0.010760  0.009765  0.010051  89034825.0
...                       ...       ...       ...       ...         ...
2022-01-31 23:55:00  0.079560       NaN       NaN       NaN         NaN
2022-01-31 23:56:00  0.079550       NaN       NaN       NaN         NaN
2022-01-31 23:57:00  0.079530       NaN       NaN       NaN         NaN
2022-01-31 23:58:00  0.079550       NaN       NaN       NaN         NaN
2022-01-31 23:59:00  0.079520       NaN       NaN       NaN         NaN

                       symbol
date
2021-01-26 07:00:00  ANKRUSDT
2021-01-26 07:01:00  ANKRUSDT
2021-01-26 07:02:00  ANKRUSDT
2021-01-26 07:03:00  ANKRUSDT
2021-01-26 07:04:00  ANKRUSDT
...                       ...
2022-01-31 23:55:00  ANKRUSDT
2022-01-31 23:56:00  ANKRUSDT
2022-01-31 23:57:00  ANKRUSDT
2022-01-31 23:58:00  ANKRUSDT
2022-01-31 23:59:00  ANKRUSDT

[533820 rows x 6 columns]
sub_df(1)=
          date      open      high       low     close        volume    symbol
0   2021-01-27  0.010584  0.010587  0.009239  0.009923  1.284014e+08  ANKRUSDT
1   2021-01-28  0.009925  0.014072  0.009679  0.011889  6.918313e+08  ANKRUSDT
2   2021-01-29  0.011889  0.014966  0.011889  0.012541  6.048544e+08  ANKRUSDT
3   2021-01-30  0.012541  0.014065  0.011500  0.012056  3.880613e+08  ANKRUSDT
4   2021-01-31  0.012050  0.013000  0.011213  0.011600  2.663684e+08  ANKRUSDT
..         ...       ...       ...       ...       ...           ...       ...
365 2022-01-27  0.068580  0.075880  0.067050  0.071540  1.632096e+09  ANKRUSDT
366 2022-01-28  0.071500  0.073250  0.068600  0.071890  4.848246e+08  ANKRUSDT
367 2022-01-29  0.071900  0.073750  0.070370  0.072770  3.391835e+08  ANKRUSDT
368 2022-01-30  0.072740  0.081490  0.070410  0.079210  7.464444e+08  ANKRUSDT
369 2022-01-31  0.079250  0.080890  0.075140  0.079600  1.464164e+09  ANKRUSDT

[370 rows x 7 columns]
processing SNXUSDT.csv (64/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=771418),m=Int64Index([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=771418),path=testdata/source/1440d/0000/SNXUSDT.csv
sub_df(0)=
                      open  high    low  close      volume   symbol
date
2020-08-14 07:02:00  5.460  7.08  5.321  6.898  11559106.7  SNXUSDT
2020-08-14 07:03:00  5.408  7.08  5.321  6.912  11572417.5  SNXUSDT
2020-08-14 07:04:00  5.500  7.08  5.321  6.930  11567853.2  SNXUSDT
2020-08-14 07:05:00  5.499  7.08  5.321  6.884  11581250.8  SNXUSDT
2020-08-14 07:06:00  5.626  7.08  5.321  6.883  11576846.8  SNXUSDT
...                    ...   ...    ...    ...         ...      ...
2022-01-31 23:55:00  5.714   NaN    NaN    NaN         NaN  SNXUSDT
2022-01-31 23:56:00  5.725   NaN    NaN    NaN         NaN  SNXUSDT
2022-01-31 23:57:00  5.737   NaN    NaN    NaN         NaN  SNXUSDT
2022-01-31 23:58:00  5.732   NaN    NaN    NaN         NaN  SNXUSDT
2022-01-31 23:59:00  5.737   NaN    NaN    NaN         NaN  SNXUSDT

[771418 rows x 6 columns]
sub_df(1)=
          date   open   high    low  close      volume   symbol
0   2020-08-15  6.166  7.483  5.905  6.888  14678852.0  SNXUSDT
1   2020-08-16  6.885  6.890  6.237  6.416   5091347.5  SNXUSDT
2   2020-08-17  6.418  6.902  6.078  6.163   5135367.3  SNXUSDT
3   2020-08-18  6.162  6.694  5.500  6.154   5343290.7  SNXUSDT
4   2020-08-19  6.154  6.394  5.379  6.104   8122611.2  SNXUSDT
..         ...    ...    ...    ...    ...         ...      ...
530 2022-01-27  4.619  4.986  4.380  4.564  14611704.2  SNXUSDT
531 2022-01-28  4.563  4.719  4.425  4.559   8273046.0  SNXUSDT
532 2022-01-29  4.560  5.488  4.542  5.394  13798258.3  SNXUSDT
533 2022-01-30  5.394  5.550  5.103  5.249  17193940.4  SNXUSDT
534 2022-01-31  5.249  5.806  5.018  5.728  18205774.3  SNXUSDT

[535 rows x 7 columns]
processing LINAUSDT.csv (65/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=458940),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=458940),path=testdata/source/1440d/0000/LINAUSDT.csv
sub_df(0)=
                        open     high      low    close       volume    symbol
date
2021-03-19 07:00:00  0.18000  0.20453  0.15303  0.16340  315598824.0  LINAUSDT
2021-03-19 07:01:00  0.19672  0.20453  0.15303  0.16374  315497669.0  LINAUSDT
2021-03-19 07:02:00  0.19711  0.20453  0.15303  0.16317  315776916.0  LINAUSDT
2021-03-19 07:03:00  0.19710  0.20453  0.15303  0.16221  315702928.0  LINAUSDT
2021-03-19 07:04:00  0.19889  0.20453  0.15303  0.16132  315907200.0  LINAUSDT
...                      ...      ...      ...      ...          ...       ...
2022-01-31 23:55:00  0.02443      NaN      NaN      NaN          NaN  LINAUSDT
2022-01-31 23:56:00  0.02444      NaN      NaN      NaN          NaN  LINAUSDT
2022-01-31 23:57:00  0.02446      NaN      NaN      NaN          NaN  LINAUSDT
2022-01-31 23:58:00  0.02445      NaN      NaN      NaN          NaN  LINAUSDT
2022-01-31 23:59:00  0.02444      NaN      NaN      NaN          NaN  LINAUSDT

[458940 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close        volume    symbol
0   2021-03-20  0.16921  0.17878  0.15303  0.15612  3.668387e+08  LINAUSDT
1   2021-03-21  0.15597  0.18066  0.15500  0.16977  3.056217e+08  LINAUSDT
2   2021-03-22  0.16983  0.17051  0.13200  0.14067  2.756639e+08  LINAUSDT
3   2021-03-23  0.14067  0.14770  0.12650  0.13061  3.366279e+08  LINAUSDT
4   2021-03-24  0.13035  0.14889  0.11344  0.12138  3.603829e+08  LINAUSDT
..         ...      ...      ...      ...      ...           ...       ...
313 2022-01-27  0.02253  0.02288  0.02109  0.02229  1.144219e+09  LINAUSDT
314 2022-01-28  0.02228  0.02441  0.02185  0.02413  3.140554e+09  LINAUSDT
315 2022-01-29  0.02412  0.02645  0.02407  0.02577  4.087251e+09  LINAUSDT
316 2022-01-30  0.02577  0.02594  0.02363  0.02416  1.727355e+09  LINAUSDT
317 2022-01-31  0.02414  0.02478  0.02289  0.02443  1.592288e+09  LINAUSDT

[318 rows x 7 columns]
processing RENUSDT.csv (66/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=685020),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=685020),path=testdata/source/1440d/0000/RENUSDT.csv
sub_df(0)=
                        open     high      low    close      volume   symbol
date
2020-10-13 07:00:00  0.34091  0.38003  0.32763  0.35872  28597215.0  RENUSDT
2020-10-13 07:01:00  0.36900  0.37680  0.32763  0.35772  28374801.0  RENUSDT
2020-10-13 07:02:00  0.36700  0.37680  0.32763  0.35796  28389996.0  RENUSDT
2020-10-13 07:03:00  0.36148  0.37680  0.32763  0.35797  28309283.0  RENUSDT
2020-10-13 07:04:00  0.35959  0.37680  0.32763  0.35695  28035592.0  RENUSDT
...                      ...      ...      ...      ...         ...      ...
2022-01-31 23:55:00  0.33210      NaN      NaN      NaN         NaN  RENUSDT
2022-01-31 23:56:00  0.33240      NaN      NaN      NaN         NaN  RENUSDT
2022-01-31 23:57:00  0.33300      NaN      NaN      NaN         NaN  RENUSDT
2022-01-31 23:58:00  0.33280      NaN      NaN      NaN         NaN  RENUSDT
2022-01-31 23:59:00  0.33270      NaN      NaN      NaN         NaN  RENUSDT

[685020 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close       volume   symbol
0   2020-10-14  0.34092  0.38843  0.33617  0.38444   47472651.0  RENUSDT
1   2020-10-15  0.38365  0.38500  0.35148  0.36018   22912677.0  RENUSDT
2   2020-10-16  0.36031  0.36653  0.32030  0.32439   19911224.0  RENUSDT
3   2020-10-17  0.32442  0.35500  0.31057  0.34586   13640028.0  RENUSDT
4   2020-10-18  0.34621  0.35279  0.33527  0.34524   13723800.0  RENUSDT
..         ...      ...      ...      ...      ...          ...      ...
470 2022-01-27  0.33160  0.33260  0.29200  0.30580  139376664.0  RENUSDT
471 2022-01-28  0.30570  0.33590  0.30020  0.32710  145670679.0  RENUSDT
472 2022-01-29  0.32710  0.35870  0.32130  0.34190   88512351.0  RENUSDT
473 2022-01-30  0.34200  0.35890  0.33160  0.33720  105625214.0  RENUSDT
474 2022-01-31  0.33700  0.34170  0.31650  0.33180   82871575.0  RENUSDT

[475 rows x 7 columns]
processing ALICEUSDT.csv (67/145)

h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=463500),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=463500),path=testdata/source/1440d/0000/ALICEUSDT.csv
sub_df(0)=
                       open    high     low   close     volume     symbol
date
2021-03-16 03:00:00  19.000  25.490  15.557  17.703  9104289.2  ALICEUSDT
2021-03-16 03:01:00  23.445  25.460  15.557  17.565  9084595.1  ALICEUSDT
2021-03-16 03:02:00  24.562  25.460  15.557  17.569  9072904.5  ALICEUSDT
2021-03-16 03:03:00  24.324  25.297  15.557  17.551  9066650.8  ALICEUSDT
2021-03-16 03:04:00  24.520  25.297  15.557  17.523  9065482.3  ALICEUSDT
...                     ...     ...     ...     ...        ...        ...
2022-01-31 23:55:00   6.904     NaN     NaN     NaN        NaN  ALICEUSDT
2022-01-31 23:56:00   6.907     NaN     NaN     NaN        NaN  ALICEUSDT
2022-01-31 23:57:00   6.912     NaN     NaN     NaN        NaN  ALICEUSDT
2022-01-31 23:58:00   6.909     NaN     NaN     NaN        NaN  ALICEUSDT
2022-01-31 23:59:00   6.909     NaN     NaN     NaN        NaN  ALICEUSDT

[463500 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume     symbol
0   2021-03-17  17.099  18.880  14.100  14.607   5653609.5  ALICEUSDT
1   2021-03-18  14.613  19.950  14.324  17.045  10014211.5  ALICEUSDT
2   2021-03-19  17.047  18.044  15.025  15.218   5494711.4  ALICEUSDT
3   2021-03-20  15.236  15.589  14.100  14.400   3365511.7  ALICEUSDT
4   2021-03-21  14.407  14.801  13.061  14.080   4339203.3  ALICEUSDT
..         ...     ...     ...     ...     ...         ...        ...
316 2022-01-27   6.705   6.940   6.345   6.611  22886957.5  ALICEUSDT
317 2022-01-28   6.610   6.886   6.377   6.813  16726555.6  ALICEUSDT
318 2022-01-29   6.815   7.038   6.744   6.899  13127956.8  ALICEUSDT
319 2022-01-30   6.900   7.229   6.657   6.728  15144864.9  ALICEUSDT
320 2022-01-31   6.727   6.989   6.402   6.905  17622667.9  ALICEUSDT

[321 rows x 7 columns]
processing LITUSDT.csv (68/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=500700),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=500700),path=testdata/source/1440d/0000/LITUSDT.csv
sub_df(0)=
                       open   high     low   close     volume   symbol
date
2021-02-18 07:00:00  11.010  12.97  10.161  10.993  2048098.0  LITUSDT
2021-02-18 07:01:00  12.040  12.97  10.161  10.991  2031625.5  LITUSDT
2021-02-18 07:02:00  12.353  12.97  10.161  11.003  2014972.7  LITUSDT
2021-02-18 07:03:00  12.357  12.97  10.161  11.004  2002579.5  LITUSDT
2021-02-18 07:04:00  12.234  12.97  10.161  11.039  1999718.0  LITUSDT
...                     ...    ...     ...     ...        ...      ...
2022-01-31 23:55:00   1.368    NaN     NaN     NaN        NaN  LITUSDT
2022-01-31 23:56:00   1.370    NaN     NaN     NaN        NaN  LITUSDT
2022-01-31 23:57:00   1.370    NaN     NaN     NaN        NaN  LITUSDT
2022-01-31 23:58:00   1.369    NaN     NaN     NaN        NaN  LITUSDT
2022-01-31 23:59:00   1.369    NaN     NaN     NaN        NaN  LITUSDT

[500700 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume   symbol
0   2021-02-19  11.335  11.561  10.001  10.248   2502227.3  LITUSDT
1   2021-02-20  10.255  12.500   9.404  10.335   5072291.3  LITUSDT
2   2021-02-21  10.323  11.595  10.050  10.652   2514061.8  LITUSDT
3   2021-02-22  10.654  11.164   7.173   9.167   4715959.8  LITUSDT
4   2021-02-23   9.204   9.275   6.139   7.640   3808502.2  LITUSDT
..         ...     ...     ...     ...     ...         ...      ...
342 2022-01-27   1.517   1.547   1.370   1.427   9728013.4  LITUSDT
343 2022-01-28   1.427   1.459   1.351   1.400  16676783.5  LITUSDT
344 2022-01-29   1.400   1.456   1.380   1.432  14747631.3  LITUSDT
345 2022-01-30   1.432   1.492   1.340   1.348  16220645.9  LITUSDT
346 2022-01-31   1.347   1.382   1.272   1.365  17450601.7  LITUSDT

[347 rows x 7 columns]
processing ARPAUSDT.csv (69/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=150990),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=150990),path=testdata/source/1440d/0000/ARPAUSDT.csv
sub_df(0)=
                        open     high     low    close        volume    symbol
date
2021-10-19 03:30:00  0.14761  0.19588  0.1428  0.16185  3.682410e+09  ARPAUSDT
2021-10-19 03:31:00  0.14652  0.19588  0.1428  0.16271  3.683522e+09  ARPAUSDT
2021-10-19 03:32:00  0.14650  0.19588  0.1428  0.16348  3.686085e+09  ARPAUSDT
2021-10-19 03:33:00  0.14635  0.19588  0.1428  0.16267  3.687950e+09  ARPAUSDT
2021-10-19 03:34:00  0.14534  0.19588  0.1428  0.16290  3.688888e+09  ARPAUSDT
...                      ...      ...     ...      ...           ...       ...
2022-01-31 23:55:00  0.06185      NaN     NaN      NaN           NaN  ARPAUSDT
2022-01-31 23:56:00  0.06189      NaN     NaN      NaN           NaN  ARPAUSDT
2022-01-31 23:57:00  0.06190      NaN     NaN      NaN           NaN  ARPAUSDT
2022-01-31 23:58:00  0.06189      NaN     NaN      NaN           NaN  ARPAUSDT
2022-01-31 23:59:00  0.06192      NaN     NaN      NaN           NaN  ARPAUSDT

[150990 rows x 6 columns]
sub_df(1)=
          date     open     high      low    close        volume    symbol
0   2021-10-20  0.17164  0.17300  0.15850  0.16431  1.016442e+09  ARPAUSDT
1   2021-10-21  0.16429  0.17000  0.14600  0.14935  5.423132e+08  ARPAUSDT
2   2021-10-22  0.14936  0.15710  0.14402  0.15270  3.611633e+08  ARPAUSDT
3   2021-10-23  0.15273  0.15370  0.14500  0.14769  2.093566e+08  ARPAUSDT
4   2021-10-24  0.14759  0.15158  0.13700  0.14009  2.884938e+08  ARPAUSDT
..         ...      ...      ...      ...      ...           ...       ...
99  2022-01-27  0.06431  0.07200  0.06274  0.06489  2.234440e+09  ARPAUSDT
100 2022-01-28  0.06487  0.06566  0.06119  0.06286  8.377052e+08  ARPAUSDT
101 2022-01-29  0.06286  0.06594  0.06250  0.06356  3.201774e+08  ARPAUSDT
102 2022-01-30  0.06356  0.06461  0.06100  0.06176  1.673233e+08  ARPAUSDT
103 2022-01-31  0.06175  0.06448  0.05888  0.06183  2.313940e+08  ARPAUSDT

[104 rows x 7 columns]
processing XRPBUSD.csv (70/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=253229),m=Int64Index([31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=253229),path=testdata/source/1440d/0000/XRPBUSD.csv
sub_df(0)=
                       open    high     low   close     volume   symbol
date
2021-08-09 03:31:00  0.7654  0.8284  0.7642  0.8082  1874537.7  XRPBUSD
2021-08-09 03:32:00  0.7657  0.8284  0.7642  0.8080  1875445.4  XRPBUSD
2021-08-09 03:33:00  0.7643  0.8284  0.7642  0.8090  1876325.5  XRPBUSD
2021-08-09 03:34:00  0.7748  0.8284  0.7656  0.8081  1872656.1  XRPBUSD
2021-08-09 03:35:00  0.7685  0.8284  0.7656  0.8081  1870755.1  XRPBUSD
...                     ...     ...     ...     ...        ...      ...
2022-01-31 23:55:00  0.6180     NaN     NaN     NaN        NaN  XRPBUSD
2022-01-31 23:56:00  0.6183     NaN     NaN     NaN        NaN  XRPBUSD
2022-01-31 23:57:00  0.6189     NaN     NaN     NaN        NaN  XRPBUSD
2022-01-31 23:58:00  0.6187     NaN     NaN     NaN        NaN  XRPBUSD
2022-01-31 23:59:00  0.6178     NaN     NaN     NaN        NaN  XRPBUSD

[253229 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close        volume   symbol
0   2021-08-10  0.8172  0.8629  0.8007  0.8520  3.336047e+06  XRPBUSD
1   2021-08-11  0.8519  1.0940  0.8492  1.0131  1.554886e+07  XRPBUSD
2   2021-08-12  1.0120  1.0486  0.9227  0.9666  1.669220e+07  XRPBUSD
3   2021-08-13  0.9667  1.0981  0.9516  1.0901  1.715608e+07  XRPBUSD
4   2021-08-14  1.0917  1.3123  1.0708  1.2812  2.563108e+07  XRPBUSD
..         ...     ...     ...     ...     ...           ...      ...
170 2022-01-27  0.6189  0.6244  0.5890  0.6086  5.853561e+07  XRPBUSD
171 2022-01-28  0.6085  0.6137  0.5916  0.6108  3.842667e+07  XRPBUSD
172 2022-01-29  0.6109  0.6256  0.6082  0.6175  1.930104e+07  XRPBUSD
173 2022-01-30  0.6175  0.6233  0.5972  0.6014  2.101492e+07  XRPBUSD
174 2022-01-31  0.6013  0.6244  0.5801  0.6174  3.985008e+07  XRPBUSD

[175 rows x 7 columns]
processing DEFIUSDT.csv (71/145)

h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=751260),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=751260),path=testdata/source/1440d/0000/DEFIUSDT.csv
sub_df(0)=
                       open    high    low   close     volume    symbol
date
2020-08-28 07:00:00  1012.0  1189.0  964.1  1046.7  87092.009  DEFIUSDT
2020-08-28 07:01:00  1016.8  1189.0  964.1  1046.1  87103.589  DEFIUSDT
2020-08-28 07:02:00  1024.7  1189.0  964.1  1045.8  87136.056  DEFIUSDT
2020-08-28 07:03:00  1094.7  1189.0  964.1  1046.0  87029.750  DEFIUSDT
2020-08-28 07:04:00  1079.0  1189.0  964.1  1046.5  86866.278  DEFIUSDT
...                     ...     ...    ...     ...        ...       ...
2022-01-31 23:55:00  1680.8     NaN    NaN     NaN        NaN  DEFIUSDT
2022-01-31 23:56:00  1680.9     NaN    NaN     NaN        NaN  DEFIUSDT
2022-01-31 23:57:00  1682.7     NaN    NaN     NaN        NaN  DEFIUSDT
2022-01-31 23:58:00  1683.3     NaN    NaN     NaN        NaN  DEFIUSDT
2022-01-31 23:59:00  1681.2     NaN    NaN     NaN        NaN  DEFIUSDT

[751260 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close     volume    symbol
0   2020-08-29  1017.5  1096.5  1015.0  1056.0  51097.047  DEFIUSDT
1   2020-08-30  1056.0  1120.0  1056.0  1085.2  49511.952  DEFIUSDT
2   2020-08-31  1085.0  1095.2  1050.4  1061.2  36092.462  DEFIUSDT
3   2020-09-01  1062.5  1125.8  1035.7  1080.7  48126.384  DEFIUSDT
4   2020-09-02  1081.1  1093.9   930.0   992.7  63481.975  DEFIUSDT
..         ...     ...     ...     ...     ...        ...       ...
516 2022-01-27  1615.5  1664.3  1508.9  1578.6   4888.141  DEFIUSDT
517 2022-01-28  1576.2  1618.5  1505.1  1602.5   4997.551  DEFIUSDT
518 2022-01-29  1602.4  1669.9  1594.9  1639.9   4426.443  DEFIUSDT
519 2022-01-30  1641.3  1677.3  1584.1  1617.3   3726.471  DEFIUSDT
520 2022-01-31  1616.8  1685.7  1533.6  1678.6   4425.804  DEFIUSDT

[521 rows x 7 columns]
processing ZENUSDT.csv (72/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=624540),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=624540),path=testdata/source/1440d/0000/ZENUSDT.csv
sub_df(0)=
                       open    high     low   close    volume   symbol
date
2020-11-24 07:00:00  12.888  18.494  12.864  16.988  950770.5  ZENUSDT
2020-11-24 07:01:00  13.334  18.494  12.884  17.218  950272.4  ZENUSDT
2020-11-24 07:02:00  13.538  18.494  12.884  17.224  945432.7  ZENUSDT
2020-11-24 07:03:00  13.577  18.494  12.884  17.090  943763.0  ZENUSDT
2020-11-24 07:04:00  14.276  18.494  12.884  17.114  927819.4  ZENUSDT
...                     ...     ...     ...     ...       ...      ...
2022-01-31 23:55:00  41.015     NaN     NaN     NaN       NaN  ZENUSDT
2022-01-31 23:56:00  41.016     NaN     NaN     NaN       NaN  ZENUSDT
2022-01-31 23:57:00  41.038     NaN     NaN     NaN       NaN  ZENUSDT
2022-01-31 23:58:00  41.006     NaN     NaN     NaN       NaN  ZENUSDT
2022-01-31 23:59:00  41.003     NaN     NaN     NaN       NaN  ZENUSDT

[624540 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close     volume   symbol
0   2020-11-25  14.322  19.699  13.031  14.735  1894972.0  ZENUSDT
1   2020-11-26  14.728  15.432  11.087  11.857  1406867.5  ZENUSDT
2   2020-11-27  11.861  13.525  11.111  12.259   507469.2  ZENUSDT
3   2020-11-28  12.268  15.840  11.680  14.898  1074279.2  ZENUSDT
4   2020-11-29  14.914  15.500  13.613  13.932   762906.8  ZENUSDT
..         ...     ...     ...     ...     ...        ...      ...
428 2022-01-27  36.659  38.630  34.147  36.735  1450054.1  ZENUSDT
429 2022-01-28  36.732  39.542  36.091  38.855  2205180.6  ZENUSDT
430 2022-01-29  38.854  43.700  38.689  41.522  2807433.5  ZENUSDT
431 2022-01-30  41.523  42.964  39.400  40.230   831035.9  ZENUSDT
432 2022-01-31  40.232  41.419  38.141  40.926   925105.4  ZENUSDT

[433 rows x 7 columns]
processing ADABUSD.csv (73/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=263297),m=Int64Index([43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=263297),path=testdata/source/1440d/0000/ADABUSD.csv
sub_df(0)=
                       open    high     low   close    volume   symbol
date
2021-08-02 03:43:00  1.3214  1.3472  1.2825  1.2834  961429.0  ADABUSD
2021-08-02 03:44:00  1.3214  1.3472  1.2823  1.2823  961151.0  ADABUSD
2021-08-02 03:45:00  1.3214  1.3472  1.2814  1.2814  962156.0  ADABUSD
2021-08-02 03:46:00  1.3217  1.3472  1.2805  1.2820  963845.0  ADABUSD
2021-08-02 03:47:00  1.3218  1.3472  1.2804  1.2832  964421.0  ADABUSD
...                     ...     ...     ...     ...       ...      ...
2022-01-31 23:55:00  1.0512     NaN     NaN     NaN       NaN  ADABUSD
2022-01-31 23:56:00  1.0523     NaN     NaN     NaN       NaN  ADABUSD
2022-01-31 23:57:00  1.0522     NaN     NaN     NaN       NaN  ADABUSD
2022-01-31 23:58:00  1.0520     NaN     NaN     NaN       NaN  ADABUSD
2022-01-31 23:59:00  1.0514     NaN     NaN     NaN       NaN  ADABUSD

[263297 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume   symbol
0   2021-08-03  1.3082  1.3826  1.2609  1.3694   3134820.0  ADABUSD
1   2021-08-04  1.3700  1.3938  1.3227  1.3760   4203089.0  ADABUSD
2   2021-08-05  1.3761  1.3981  1.3378  1.3870   3280291.0  ADABUSD
3   2021-08-06  1.3870  1.4260  1.3625  1.4026   4011599.0  ADABUSD
4   2021-08-07  1.4027  1.4875  1.3955  1.4741   5698783.0  ADABUSD
..         ...     ...     ...     ...     ...         ...      ...
177 2022-01-27  1.0773  1.0797  1.0040  1.0420  83983611.0  ADABUSD
178 2022-01-28  1.0417  1.0587  1.0080  1.0478  60742617.0  ADABUSD
179 2022-01-29  1.0478  1.0835  1.0374  1.0594  34863765.0  ADABUSD
180 2022-01-30  1.0594  1.0768  1.0235  1.0347  33553937.0  ADABUSD
181 2022-01-31  1.0349  1.0588  1.0077  1.0512  46489033.0  ADABUSD

[182 rows x 7 columns]
processing BANDUSDT.csv (74/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=794460),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=794460),path=testdata/source/1440d/0000/BANDUSDT.csv
sub_df(0)=
                       open    high     low   close     volume    symbol
date
2020-07-29 07:00:00  3.8400  3.9893  3.7396  3.8118  5782117.6  BANDUSDT
2020-07-29 07:01:00  3.8198  3.9893  3.7396  3.8114  5786801.3  BANDUSDT
2020-07-29 07:02:00  3.8185  3.9893  3.7396  3.8113  5767098.9  BANDUSDT
2020-07-29 07:03:00  3.8157  3.9893  3.7396  3.8114  5755419.3  BANDUSDT
2020-07-29 07:04:00  3.8150  3.9893  3.7396  3.8113  5743489.7  BANDUSDT
...                     ...     ...     ...     ...        ...       ...
2022-01-31 23:55:00  3.4791     NaN     NaN     NaN        NaN  BANDUSDT
2022-01-31 23:56:00  3.4842     NaN     NaN     NaN        NaN  BANDUSDT
2022-01-31 23:57:00  3.4829     NaN     NaN     NaN        NaN  BANDUSDT
2022-01-31 23:58:00  3.4824     NaN     NaN     NaN        NaN  BANDUSDT
2022-01-31 23:59:00  3.4783     NaN     NaN     NaN        NaN  BANDUSDT

[794460 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close        volume    symbol
0   2020-07-30  3.8951  4.2990  3.7396  3.9774  1.032568e+07  BANDUSDT
1   2020-07-31  3.9812  4.3832  3.9526  4.2311  1.397827e+07  BANDUSDT
2   2020-08-01  4.2334  4.2988  3.9828  4.0093  1.394249e+07  BANDUSDT
3   2020-08-02  4.0087  4.1475  3.0598  4.0542  1.566805e+07  BANDUSDT
4   2020-08-03  4.0532  4.2489  4.0095  4.2199  1.339591e+07  BANDUSDT
..         ...     ...     ...     ...     ...           ...       ...
546 2022-01-27  3.4395  3.5029  3.2260  3.3757  7.223527e+06  BANDUSDT
547 2022-01-28  3.3748  3.5151  3.3050  3.4440  7.474930e+06  BANDUSDT
548 2022-01-29  3.4441  3.6021  3.4337  3.5111  6.297521e+06  BANDUSDT
549 2022-01-30  3.5080  3.6158  3.3880  3.4384  7.811824e+06  BANDUSDT
550 2022-01-31  3.4386  3.4896  3.2064  3.4776  7.509203e+06  BANDUSDT

[551 rows x 7 columns]
processing IOTAUSDT.csv (75/145)

h=Int64Index([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=1036320),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=1036320),path=testdata/source/1440d/0000/IOTAUSDT.csv
sub_df(0)=
                       open    high     low   close      volume    symbol
date
2020-02-12 08:00:00  0.3380  0.3725  0.3218  0.3335  33003945.5  IOTAUSDT
2020-02-12 08:01:00  0.3380  0.3725  0.3218  0.3346  33080345.8  IOTAUSDT
2020-02-12 08:02:00  0.3386  0.3725  0.3218  0.3359  33082722.5  IOTAUSDT
2020-02-12 08:03:00  0.3385  0.3725  0.3218  0.3368  33068261.7  IOTAUSDT
2020-02-12 08:04:00  0.3382  0.3725  0.3218  0.3369  32977050.7  IOTAUSDT
...                     ...     ...     ...     ...         ...       ...
2022-01-31 23:55:00  0.8348     NaN     NaN     NaN         NaN  IOTAUSDT
2022-01-31 23:56:00  0.8348     NaN     NaN     NaN         NaN  IOTAUSDT
2022-01-31 23:57:00  0.8349     NaN     NaN     NaN         NaN  IOTAUSDT
2022-01-31 23:58:00  0.8341     NaN     NaN     NaN         NaN  IOTAUSDT
2022-01-31 23:59:00  0.8336     NaN     NaN     NaN         NaN  IOTAUSDT

[1036320 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close        volume    symbol
0   2020-02-13  0.3315  0.3489  0.3033  0.3227  2.930154e+07  IOTAUSDT
1   2020-02-14  0.3226  0.3289  0.3109  0.3242  2.148653e+07  IOTAUSDT
2   2020-02-15  0.3245  0.3269  0.2781  0.2875  1.898144e+07  IOTAUSDT
3   2020-02-16  0.2876  0.2976  0.1798  0.2775  1.492966e+07  IOTAUSDT
4   2020-02-17  0.2775  0.2863  0.2528  0.2831  1.048188e+07  IOTAUSDT
..         ...     ...     ...     ...     ...           ...       ...
714 2022-01-27  0.8024  0.8317  0.7663  0.8011  3.535975e+07  IOTAUSDT
715 2022-01-28  0.8010  0.8216  0.7740  0.8166  2.874417e+07  IOTAUSDT
716 2022-01-29  0.8164  0.8465  0.8134  0.8303  2.029415e+07  IOTAUSDT
717 2022-01-30  0.8306  0.8519  0.8004  0.8130  1.859971e+07  IOTAUSDT
718 2022-01-31  0.8127  0.8387  0.7808  0.8329  2.379952e+07  IOTAUSDT

[719 rows x 7 columns]
processing KEEPUSDT.csv (76/145)
h=Int64Index([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=322350),m=Int64Index([30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=322350),path=testdata/source/1440d/0000/KEEPUSDT.csv
sub_df(0)=
                       open  high     low   close      volume    symbol
date
2021-06-22 03:30:00  0.3119  0.33  0.2348  0.2829  61404718.0  KEEPUSDT
2021-06-22 03:31:00  0.3015  0.33  0.2348  0.2827  61341460.0  KEEPUSDT
2021-06-22 03:32:00  0.3032  0.33  0.2348  0.2831  61325383.0  KEEPUSDT
2021-06-22 03:33:00  0.2986  0.33  0.2348  0.2819  61294829.0  KEEPUSDT
2021-06-22 03:34:00  0.2972  0.33  0.2348  0.2818  61115117.0  KEEPUSDT
...                     ...   ...     ...     ...         ...       ...
2022-01-31 23:55:00  0.4467   NaN     NaN     NaN         NaN  KEEPUSDT
2022-01-31 23:56:00  0.4471   NaN     NaN     NaN         NaN  KEEPUSDT
2022-01-31 23:57:00  0.4471   NaN     NaN     NaN         NaN  KEEPUSDT
2022-01-31 23:58:00  0.4469   NaN     NaN     NaN         NaN  KEEPUSDT
2022-01-31 23:59:00  0.4469   NaN     NaN     NaN         NaN  KEEPUSDT

[322350 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close       volume    symbol
0   2021-06-23  0.2505  0.2999  0.2348  0.2710   33580510.0  KEEPUSDT
1   2021-06-24  0.2710  0.2871  0.2532  0.2697   14732773.0  KEEPUSDT
2   2021-06-25  0.2697  0.2862  0.2419  0.2423   22714356.0  KEEPUSDT
3   2021-06-26  0.2426  0.2495  0.2233  0.2448   20928297.0  KEEPUSDT
4   2021-06-27  0.2450  0.2980  0.2425  0.2962  100463625.0  KEEPUSDT
..         ...     ...     ...     ...     ...          ...       ...
218 2022-01-27  0.4075  0.4221  0.3808  0.3949   51676729.0  KEEPUSDT
219 2022-01-28  0.3947  0.4161  0.3884  0.4136   48066537.0  KEEPUSDT
220 2022-01-29  0.4138  0.4434  0.4109  0.4352   75515762.0  KEEPUSDT
221 2022-01-30  0.4351  0.4605  0.4187  0.4286   44568428.0  KEEPUSDT
222 2022-01-31  0.4285  0.4553  0.4065  0.4461   44229006.0  KEEPUSDT

[223 rows x 7 columns]
processing MTLUSDT.csv (77/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=441660),m=Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=441660),path=testdata/source/1440d/0000/MTLUSDT.csv
sub_df(0)=
                       open    high   low   close     volume   symbol
date
2021-03-31 07:00:00  7.2106  7.2106  5.62  5.9446  9095307.0  MTLUSDT
2021-03-31 07:01:00  6.6420  6.9874  5.62  5.8869  9145920.0  MTLUSDT
2021-03-31 07:02:00  6.6600  6.9874  5.62  5.9500  9182324.0  MTLUSDT
2021-03-31 07:03:00  6.6263  6.9874  5.62  5.9301  9193634.0  MTLUSDT
2021-03-31 07:04:00  6.6900  6.9874  5.62  5.9004  9200290.0  MTLUSDT
...                     ...     ...   ...     ...        ...      ...
2022-01-31 23:55:00  1.5442     NaN   NaN     NaN        NaN  MTLUSDT
2022-01-31 23:56:00  1.5439     NaN   NaN     NaN        NaN  MTLUSDT
2022-01-31 23:57:00  1.5442     NaN   NaN     NaN        NaN  MTLUSDT
2022-01-31 23:58:00  1.5444     NaN   NaN     NaN        NaN  MTLUSDT
2022-01-31 23:59:00  1.5448     NaN   NaN     NaN        NaN  MTLUSDT

[441660 rows x 6 columns]
sub_df(1)=
          date    open    high     low   close      volume   symbol
0   2021-04-01  5.9566  6.3949  5.5386  5.5661   9093496.0  MTLUSDT
1   2021-04-02  5.5674  5.5690  5.0384  5.1322   6860573.0  MTLUSDT
2   2021-04-03  5.1398  6.8226  5.0519  6.6871  15056630.0  MTLUSDT
3   2021-04-04  6.7103  6.9687  5.8394  6.8858  15692999.0  MTLUSDT
4   2021-04-05  6.8861  6.9000  5.5718  5.6179   6779281.0  MTLUSDT
..         ...     ...     ...     ...     ...         ...      ...
301 2022-01-27  1.3978  1.4330  1.3356  1.4002  10747793.0  MTLUSDT
302 2022-01-28  1.3998  1.4407  1.3653  1.4370   8078423.0  MTLUSDT
303 2022-01-29  1.4371  1.5090  1.4341  1.4916   7986551.0  MTLUSDT
304 2022-01-30  1.4924  1.5242  1.4481  1.4814   7258469.0  MTLUSDT
305 2022-01-31  1.4813  1.5569  1.3987  1.5439   9509532.0  MTLUSDT

[306 rows x 7 columns]
processing CRVUSDT.csv (78/145)
h=Int64Index([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
            ...
            23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
           dtype='int64', name='date', length=745499),m=Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
            ...
            50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64', name='date', length=745499),path=testdata/source/1440d/0000/CRVUSDT.csv
sub_df(0)=
                      open   high   low  close      volume   symbol
date
2020-09-01 07:01:00  4.600  5.748  4.49  4.874  27144452.8  CRVUSDT
2020-09-01 07:02:00  5.103  5.748  4.49  4.879  27141045.2  CRVUSDT
2020-09-01 07:03:00  4.694  5.748  4.49  4.892  27078727.6  CRVUSDT
2020-09-01 07:04:00  4.740  5.748  4.49  4.867  27038168.5  CRVUSDT
2020-09-01 07:05:00  4.783  5.748  4.49  4.863  27011501.0  CRVUSDT
...                    ...    ...   ...    ...         ...      ...
2022-01-31 23:55:00  3.293    NaN   NaN    NaN         NaN  CRVUSDT
2022-01-31 23:56:00  3.291    NaN   NaN    NaN         NaN  CRVUSDT
2022-01-31 23:57:00  3.295    NaN   NaN    NaN         NaN  CRVUSDT
2022-01-31 23:58:00  3.290    NaN   NaN    NaN         NaN  CRVUSDT
2022-01-31 23:59:00  3.277    NaN   NaN    NaN         NaN  CRVUSDT

[745499 rows x 6 columns]
sub_df(1)=
          date   open   high    low  close        volume   symbol
0   2020-09-02  5.364  5.393  3.718  4.333  2.149881e+07  CRVUSDT
1   2020-09-03  4.334  4.371  2.693  2.920  2.181266e+07  CRVUSDT
2   2020-09-04  2.920  3.296  2.698  2.860  1.360686e+07  CRVUSDT
3   2020-09-05  2.857  3.069  1.570  1.903  1.889994e+07  CRVUSDT
4   2020-09-06  1.902  2.337  1.521  2.164  1.908785e+07  CRVUSDT
..         ...    ...    ...    ...    ...           ...      ...
512 2022-01-27  2.867  2.941  2.646  2.780  7.877707e+07  CRVUSDT
513 2022-01-28  2.780  2.951  2.690  2.914  6.254083e+07  CRVUSDT
514 2022-01-29  2.914  3.083  2.890  2.989  4.890928e+07  CRVUSDT
515 2022-01-30  2.989  3.267  2.923  3.180  8.382395e+07  CRVUSDT
516 2022-01-31  3.179  3.325  2.942  3.268  8.008950e+07  CRVUSDT

[517 rows x 7 columns]
processing CHZUSDT.csv (79/145)

KeyboardInterrupt: